import tailwindcss from '@tailwindcss/vite';
import react from '@vitejs/plugin-react';
import path from 'path';
import {defineConfig} from 'vite';
import fs from 'fs';

// Recursively copy directory synchronously
function copyDirSync(src: string, dest: string) {
  if (!fs.existsSync(src)) return;
  if (!fs.existsSync(dest)) {
    fs.mkdirSync(dest, { recursive: true });
  }
  const entries = fs.readdirSync(src, { withFileTypes: true });
  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);
    if (entry.isDirectory()) {
      copyDirSync(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

// Automatically copy root 'resized_jpg' to 'public/resized_jpg' before scanning files
try {
  const rootSrc = path.resolve(process.cwd(), 'resized_jpg');
  const publicDest = path.resolve(process.cwd(), 'public/resized_jpg');
  if (fs.existsSync(rootSrc)) {
    console.log('[Vite Image Setup] Copying resized_jpg to public/resized_jpg for build/dev server...');
    copyDirSync(rootSrc, publicDest);
  }
} catch (e) {
  console.error('[Vite Image Setup] Failed to copy images:', e);
}

// Scan public/images or public/resized_jpg/resized_images for available images
const possibleDirs = ['public/images', 'public/resized_jpg/resized_images'];
let targetDir = '';
let detectedFolder = 'images';
let detected: string[] = [];

for (const dir of possibleDirs) {
  const fullPath = path.resolve(process.cwd(), dir);
  if (fs.existsSync(fullPath)) {
    targetDir = fullPath;
    detectedFolder = dir.replace('public/', '');
    break;
  }
}

if (targetDir) {
  try {
    detected = fs.readdirSync(targetDir).filter(f => {
      const ext = path.extname(f).toLowerCase();
      return ext === '.webp' || ext === '.png' || ext === '.jpg' || ext === '.jpeg';
    });
  } catch (e) {
    console.error(`Error reading ${detectedFolder} directory:`, e);
  }
}

const outputPath = path.resolve(process.cwd(), 'src/utils/detectedImages.ts');
const fileContent = `// Automatically generated by vite.config.ts at build/dev time. Do not edit directly.
export const DETECTED_IMAGES: string[] = ${JSON.stringify(detected, null, 2)};
export const DETECTED_FOLDER: string = ${JSON.stringify(detectedFolder)};
`;

try {
  fs.writeFileSync(outputPath, fileContent, 'utf-8');
  console.log(`[Vite Image Detector] Detected ${detected.length} local images in public/Resized 1080.`);
} catch (e) {
  console.error('Failed to write detected images config:', e);
}

export default defineConfig(() => {
  return {
    plugins: [
      react(), 
      tailwindcss(),
      {
        name: 'request-logger',
        configureServer(server) {
          server.middlewares.use((req, res, next) => {
            if (req.url && (req.url.includes('.webp') || req.url.includes('.png') || req.url.includes('.jpg'))) {
              res.on('finish', () => {
                const logLine = `[${new Date().toISOString()}] ${req.method} ${req.url} - Status: ${res.statusCode}\n`;
                try {
                  fs.appendFileSync('requests.log', logLine);
                } catch (err) {}
              });
            }
            next();
          });
        }
      }
    ],
    resolve: {
      alias: {
        '@': path.resolve(__dirname, '.'),
      },
    },
    server: {
      // HMR is disabled via DISABLE_HMR env var.
      // Do not modify—file watching is disabled to prevent flickering during agent edits.
      hmr: process.env.DISABLE_HMR !== 'true',
      // Disable file watching when DISABLE_HMR is true to save CPU during active edits.
      watch: process.env.DISABLE_HMR === 'true' ? null : {},
    },
  };
});
