const fs = require("fs");
const path = require("path");

const userCsvText = `Product ID,Product Name,Reviewer Name,Rating (1-5),Review Date,Review Text
TBZ-0001,Willie's Remedy THC Infused Seltzer Strawberry Watermelon,Xan Pruitt,5,"March 21, 2026","Decent, but a bit mixed for me. It's a refreshing, easy-drinking option for something low-key. Nice alternative to a cocktail on a night out. One small thing - wish the flavor was a little stronger. At around $7.99, I think it's fairly priced for a drink of this quality. Fine for the price, wouldn't go out of my way for it though."
TBZ-0001,Willie's Remedy THC Infused Seltzer Strawberry Watermelon,Oakley Dunham,5,"July 5, 2026","Decent, but a bit mixed for me. It's a refreshing, easy-drinking option for something low-key. Good option when i want to skip alcohol but still unwind. The Flower Mound TwoBudz team recommended this one and it didn't disappoint. One small thing - packaging could be better sealed. At around $7.99, I think it's fairly priced for a drink of this quality. Might try a different flavor or size next time."
TBZ-0001,Willie's Remedy THC Infused Seltzer Strawberry Watermelon,Amara Jensen,4,"May 20, 2026","Solid pick overall, just a couple small notes. It's a refreshing, easy-drinking option for something low-key. Nice alternative to a cocktail on a night out. The Flower Mound TwoBudz team recommended this one and it didn't disappoint. At around $7.99, I think it's fairly priced for a drink of this quality. Worth it even with the small downside."
TBZ-0001,Willie's Remedy THC Infused Seltzer Strawberry Watermelon,Mika B.,4,"June 24, 2026","Decent, but a bit mixed for me. It's a refreshing, easy-drinking option for something low-key. Good option when i want to skip alcohol but still unwind. One small thing - flavor was a bit more muted than I hoped. At around $7.99, I think it's fairly priced for a drink of this quality. Not bad, but I'll probably look at other options too."
TBZ-0001,Willie's Remedy THC Infused Seltzer Strawberry Watermelon,Brennan L.,5,"June 22, 2026","Really happy with this one. It's a refreshing, easy-drinking option for something low-key. Good option when i want to skip alcohol but still unwind. At around $7.99, I think it's fairly priced for a drink of this quality. This earned a permanent spot on my shopping list."
TBZ-0002,Willie's Remedy THC Infused Seltzer Black Cherry Lime,Brennan,5,"February 27, 2026","It's fine - does the job, nothing exceptional. Easy to dose out with the dropper, and it mixes in cleanly if you're adding it to a drink or taking it straight. Part of my morning wellness routine now. One small thing - would like a slightly bigger size option. At around $7.99, I think it's fairly priced for a oil/tincture of this quality. Not bad, but I'll probably look at other options too."
TBZ-0002,Willie's Remedy THC Infused Seltzer Black Cherry Lime,Yael Underwood,4,"June 15, 2026","Really good, though not quite perfect. Easy to dose out with the dropper, and it mixes in cleanly if you're adding it to a drink or taking it straight. Easy to work into a daily cbd routine. At around $7.99, I think it's fairly priced for a oil/tincture of this quality. Would still buy again."
TBZ-0002,Willie's Remedy THC Infused Seltzer Black Cherry Lime,Avery R.,5,"February 8, 2026","Glad I tried it - a few minor things keep it from a perfect score. Easy to dose out with the dropper, and it mixes in cleanly if you're adding it to a drink or taking it straight. Part of my morning wellness routine now. At around $7.99, I think it's fairly priced for a oil/tincture of this quality. Minor gripes aside, I'd repurchase."
TBZ-0002,Willie's Remedy THC Infused Seltzer Black Cherry Lime,Lior Young,5,"June 25, 2026","Really good, though not quite perfect. Easy to dose out with the dropper, and it mixes in cleanly if you're adding it to a drink or taking it straight. Part of my morning wellness routine now. At around $7.99, I think it's fairly priced for a oil/tincture of this quality. Worth it even with the small downside."
TBZ-0002,Willie's Remedy THC Infused Seltzer Black Cherry Lime,Micah,5,"July 24, 2026","Honestly one of my favorite finds at this store. Easy to dose out with the dropper, and it mixes in cleanly if you're adding it to a drink or taking it straight. Good for daily stress management. At around $7.99, I think it's fairly priced for a oil/tincture of this quality. Great value for the price."
TBZ-0003,Willie's THC Social Tonic 5mg,Elliot E.,4,"January 28, 2026","Didn't expect to like this as much as I do. Easy to dose out with the dropper, and it mixes in cleanly if you're adding it to a drink or taking it straight. Good for daily stress management. At around $54.99, I think it's fairly priced for a oil/tincture of this quality. Would buy again."
TBZ-0003,Willie's THC Social Tonic 5mg,Devon Turner,4,"March 25, 2026","Really happy with this one. Easy to dose out with the dropper, and it mixes in cleanly if you're adding it to a drink or taking it straight. Helps take the edge off before a busy day. At around $54.99, I think it's fairly priced for a oil/tincture of this quality. Will be back for more."
TBZ-0003,Willie's THC Social Tonic 5mg,Zion S.,5,"January 14, 2026","Better than I expected. Easy to dose out with the dropper, and it mixes in cleanly if you're adding it to a drink or taking it straight. Helps take the edge off before a busy day. At around $54.99, I think it's fairly priced for a oil/tincture of this quality. Will be back for more."
TBZ-0003,Willie's THC Social Tonic 5mg,Dario,5,"July 26, 2026","Really happy with this one. Easy to dose out with the dropper, and it mixes in cleanly if you're adding it to a drink or taking it straight. Easy to work into a daily cbd routine. At around $54.99, I think it's fairly priced for a oil/tincture of this quality. This earned a permanent spot on my shopping list."
TBZ-0003,Willie's THC Social Tonic 5mg,Mika P.,5,"June 8, 2026","Impressed from the first time I tried it. Easy to dose out with the dropper, and it mixes in cleanly if you're adding it to a drink or taking it straight. Helps take the edge off before a busy day. At around $54.99, I think it's fairly priced for a oil/tincture of this quality. Worth every penny."
TBZ-0004,Willie's THC Social Tonic 10mg,Sam W.,5,"January 15, 2026","Honestly one of my favorite finds at this store. Applies smoothly and absorbs quickly without leaving a greasy residue behind. Helps with joint stiffness in the morning. At around $69.99, I think it's fairly priced for a topical of this quality. Will be back for more."
TBZ-0004,Willie's THC Social Tonic 10mg,Ira Monroe,5,"March 21, 2026","Couldn't be happier with this purchase. Applies smoothly and absorbs quickly without leaving a greasy residue behind. Helps with joint stiffness in the morning. At around $69.99, I think it's fairly priced for a topical of this quality. Great value for the price."
TBZ-0004,Willie's THC Social Tonic 10mg,Emery Vance,5,"June 17, 2026","Solid pick overall, just a couple small notes. Applies smoothly and absorbs quickly without leaving a greasy residue behind. Part of my post-workout recovery routine. At around $69.99, I think it's fairly priced for a topical of this quality. Solid enough that I'll grab it again."
TBZ-0004,Willie's THC Social Tonic 10mg,Esme Dunham,5,"March 16, 2026","Really happy with this one. Applies smoothly and absorbs quickly without leaving a greasy residue behind. Good for sore muscles after a workout. At around $69.99, I think it's fairly priced for a topical of this quality. Worth every penny."
TBZ-0004,Willie's THC Social Tonic 10mg,Harper Anderson,5,"July 27, 2026","Honestly one of my favorite finds at this store. Applies smoothly and absorbs quickly without leaving a greasy residue behind. Good for tension after a long day on my feet. At around $69.99, I think it's fairly priced for a topical of this quality. Would buy again."
TBZ-0006,Wyld CBD Sparkling Water - Lemon 50mg,Adrian Monroe,5,"May 23, 2026","Better than I expected. The Lemon flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. A solid alcohol-free option for get-togethers. At around $5.99, I think it's fairly priced for a drink of this quality. Worth every penny."
TBZ-0006,Wyld CBD Sparkling Water - Lemon 50mg,Jules X.,5,"January 28, 2026","Didn't expect to like this as much as I do. The Lemon flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Nice alternative to a cocktail on a night out. At around $5.99, I think it's fairly priced for a drink of this quality. Already recommended it to a friend."
TBZ-0006,Wyld CBD Sparkling Water - Lemon 50mg,Sawyer U.,5,"January 19, 2026","Impressed from the first time I tried it. The Lemon flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Nice alternative to a cocktail on a night out. The Flower Mound TwoBudz team recommended this one and it didn't disappoint. At around $5.99, I think it's fairly priced for a drink of this quality. This earned a permanent spot on my shopping list."
TBZ-0006,Wyld CBD Sparkling Water - Lemon 50mg,Vance A.,4,"April 23, 2026","Really good, though not quite perfect. The Lemon flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Good option when i want to skip alcohol but still unwind. The Flower Mound TwoBudz team recommended this one and it didn't disappoint. At around $5.99, I think it's fairly priced for a drink of this quality. Would still buy again."
TBZ-0006,Wyld CBD Sparkling Water - Lemon 50mg,Brennan Kessler,5,"June 16, 2026","Couldn't be happier with this purchase. The Lemon flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Good option when i want to skip alcohol but still unwind. At around $5.99, I think it's fairly priced for a drink of this quality. Will be back for more."
TBZ-0007,Wyld CBD Sparkling Water - Raspberry 50mg,Winter Griffin,4,"February 8, 2026","Glad I tried it - a few minor things keep it from a perfect score. The Raspberry flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Nice alternative to a cocktail on a night out. At around $5.99, I think it's fairly priced for a drink of this quality. Worth it even with the small downside."
TBZ-0007,Wyld CBD Sparkling Water - Raspberry 50mg,Lior P.,3,"April 21, 2026","It's fine - does the job, nothing exceptional. The Raspberry flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Good for a relaxed evening without the hangover. One small thing - wish the flavor was a little stronger. At around $5.99, I think it's fairly priced for a drink of this quality. Might try a different flavor or size next time."
TBZ-0007,Wyld CBD Sparkling Water - Raspberry 50mg,Rowan Turner,3,"May 1, 2026","Middle-of-the-road experience, some pros and cons. The Raspberry flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. An easy swap for beer at a barbecue. One small thing - the size felt a little small for the price. At around $5.99, I think it's fairly priced for a drink of this quality. Fine for the price, wouldn't go out of my way for it though."
TBZ-0007,Wyld CBD Sparkling Water - Raspberry 50mg,Winter Kessler,3,"January 12, 2026","It's fine - does the job, nothing exceptional. The Raspberry flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Good for a relaxed evening without the hangover. One small thing - wish the flavor was a little stronger. At around $5.99, I think it's fairly priced for a drink of this quality. Not bad, but I'll probably look at other options too."
TBZ-0007,Wyld CBD Sparkling Water - Raspberry 50mg,Noel Turner,5,"April 18, 2026","This has become a regular pickup for me. The Raspberry flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Nice alternative to a cocktail on a night out. At around $5.99, I think it's fairly priced for a drink of this quality. Would buy again."
TBZ-0008,Enjoy Sleep 3300mg CBD + CBN Mixed Fruit Gummies,Jesse B.,4,"March 18, 2026","Really good, though not quite perfect. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for a mellow weekend afternoon. Found it during a visit to the Flower Mound shop and it's been in my rotation since. At around $5.99, I think it's fairly priced for a gummy of this quality. Worth it even with the small downside."
TBZ-0008,Enjoy Sleep 3300mg CBD + CBN Mixed Fruit Gummies,Shawn Jensen,5,"March 27, 2026","This is now a staple in my rotation. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Great for winding down after work. At around $5.99, I think it's fairly priced for a gummy of this quality. Already recommended it to a friend."
TBZ-0008,Enjoy Sleep 3300mg CBD + CBN Mixed Fruit Gummies,Ursula Sutton,5,"June 20, 2026","Impressed from the first time I tried it. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for a mellow weekend afternoon. At around $5.99, I think it's fairly priced for a gummy of this quality. Would buy again."
TBZ-0008,Enjoy Sleep 3300mg CBD + CBN Mixed Fruit Gummies,Cameron,5,"April 12, 2026","Better than I expected. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Works well as a low-key nighttime routine. At around $5.99, I think it's fairly priced for a gummy of this quality. Worth every penny."
TBZ-0008,Enjoy Sleep 3300mg CBD + CBN Mixed Fruit Gummies,Kit Underwood,3,"February 16, 2026","Decent, but a bit mixed for me. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for a mellow weekend afternoon. One small thing - the size felt a little small for the price. At around $5.99, I think it's fairly priced for a gummy of this quality. Worth trying once to see if it's for you."
TBZ-0009,Wyld Marionberry Indica THC Gummies - 10mg,Priya V.,4,"June 18, 2026","Really good, though not quite perfect. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for a mellow weekend afternoon. At around $64.99, I think it's fairly priced for a gummy of this quality. Solid enough that I'll grab it again."
TBZ-0009,Wyld Marionberry Indica THC Gummies - 10mg,Uma E.,5,"June 4, 2026","This quickly became my go-to. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. A nice option for easing into sleep. At around $64.99, I think it's fairly priced for a gummy of this quality. Would buy again."
TBZ-0009,Wyld Marionberry Indica THC Gummies - 10mg,Blake,3,"April 21, 2026","It's fine - does the job, nothing exceptional. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for a mellow weekend afternoon. One small thing - packaging could be better sealed. At around $64.99, I think it's fairly priced for a gummy of this quality. Fine for the price, wouldn't go out of my way for it though."
TBZ-0009,Wyld Marionberry Indica THC Gummies - 10mg,Alex Dunham,5,"July 24, 2026","Really happy with this one. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. A nice option for easing into sleep. At around $64.99, I think it's fairly priced for a gummy of this quality. Already recommended it to a friend."
TBZ-0009,Wyld Marionberry Indica THC Gummies - 10mg,Parker Bishop,5,"January 24, 2026","Really happy with this one. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for a mellow weekend afternoon. At around $64.99, I think it's fairly priced for a gummy of this quality. Great value for the price."
TBZ-0010,Nowadays 10mg THC Shot,Amara T.,3,"April 28, 2026","Decent, but a bit mixed for me. It's a refreshing, easy-drinking option for something low-key. Good option when i want to skip alcohol but still unwind. One small thing - packaging could be better sealed. At around $7.99, I think it's fairly priced for a drink of this quality. Not bad, but I'll probably look at other options too."
TBZ-0010,Nowadays 10mg THC Shot,Gia,4,"March 11, 2026","Good experience overall with one small nitpick. It's a refreshing, easy-drinking option for something low-key. Good option when i want to skip alcohol but still unwind. At around $7.99, I think it's fairly priced for a drink of this quality. Worth it even with the small downside."
TBZ-0010,Nowadays 10mg THC Shot,Ira S.,5,"January 8, 2026","Didn't expect to like this as much as I do. It's a refreshing, easy-drinking option for something low-key. Good option when i want to skip alcohol but still unwind. At around $7.99, I think it's fairly priced for a drink of this quality. Would buy again."
TBZ-0010,Nowadays 10mg THC Shot,Esme F.,5,"March 13, 2026","Really happy with this one. It's a refreshing, easy-drinking option for something low-key. Good for a relaxed evening without the hangover. At around $7.99, I think it's fairly priced for a drink of this quality. This earned a permanent spot on my shopping list."
TBZ-0010,Nowadays 10mg THC Shot,Uma D.,5,"July 18, 2026","This is now a staple in my rotation. It's a refreshing, easy-drinking option for something low-key. Good option when i want to skip alcohol but still unwind. Grabbed this at the TwoBudz Flower Mound location on a recommendation from a staff member. At around $7.99, I think it's fairly priced for a drink of this quality. Would buy again."
TBZ-0011,Proleve CBD Roll-On Cooling 2000mg,Yusuf I.,3,"June 21, 2026","It's fine - does the job, nothing exceptional. Applies smoothly and absorbs quickly without leaving a greasy residue behind. Part of my post-workout recovery routine. Picked it up at the Flower Mound store and the staff pointed me toward it - glad they did. One small thing - would like a slightly bigger size option. At around $39.99, I think it's fairly priced for a topical of this quality. Worth trying once to see if it's for you."
TBZ-0011,Proleve CBD Roll-On Cooling 2000mg,Esme Monroe,4,"February 19, 2026","Solid pick overall, just a couple small notes. Applies smoothly and absorbs quickly without leaving a greasy residue behind. Helps with joint stiffness in the morning. At around $39.99, I think it's fairly priced for a topical of this quality. Worth it even with the small downside."
TBZ-0011,Proleve CBD Roll-On Cooling 2000mg,Yael Ibarra,5,"January 20, 2026","Impressed from the first time I tried it. Applies smoothly and absorbs quickly without leaving a greasy residue behind. Good for sore muscles after a workout. At around $39.99, I think it's fairly priced for a topical of this quality. This earned a permanent spot on my shopping list."
TBZ-0011,Proleve CBD Roll-On Cooling 2000mg,Ira,5,"July 15, 2026","Really happy with this one. Applies smoothly and absorbs quickly without leaving a greasy residue behind. Helps with joint stiffness in the morning. At around $39.99, I think it's fairly priced for a topical of this quality. This earned a permanent spot on my shopping list."
TBZ-0011,Proleve CBD Roll-On Cooling 2000mg,Kai W.,5,"January 13, 2026","This is now a staple in my rotation. Applies smoothly and absorbs quickly without leaving a greasy residue behind. Helps with joint stiffness in the morning. At around $39.99, I think it's fairly priced for a topical of this quality. Great value for the price."
TBZ-0012,Enjoy Balance THC + CBD,Priya S.,5,"May 11, 2026","Better than I expected. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Helps me relax without feeling knocked out. At around $59.99, I think it's fairly priced for a gummy of this quality. Great value for the price."
TBZ-0012,Enjoy Balance THC + CBD,Yael A.,5,"July 21, 2026","Didn't expect to like this as much as I do. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. A nice option for easing into sleep. At around $59.99, I think it's fairly priced for a gummy of this quality. Great value for the price."
TBZ-0012,Enjoy Balance THC + CBD,Kai Lambert,5,"June 26, 2026","This quickly became my go-to. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for a mellow weekend afternoon. At around $59.99, I think it's fairly priced for a gummy of this quality. This earned a permanent spot on my shopping list."
TBZ-0012,Enjoy Balance THC + CBD,Kit P.,5,"March 1, 2026","Better than I expected. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Helps me relax without feeling knocked out. At around $59.99, I think it's fairly priced for a gummy of this quality. Can't recommend it enough."
TBZ-0012,Enjoy Balance THC + CBD,Jules D.,4,"March 5, 2026","Solid pick overall, just a couple small notes. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Helps me relax without feeling knocked out. At around $59.99, I think it's fairly priced for a gummy of this quality. Worth it even with the small downside."
TBZ-0013,Barney's Botanicals 12mg Delta 9 Gummies 10ct,Peyton Vance,5,"March 11, 2026","This quickly became my go-to. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Works well as a low-key nighttime routine. At around $19.99, I think it's fairly priced for a gummy of this quality. Would buy again."
TBZ-0013,Barney's Botanicals 12mg Delta 9 Gummies 10ct,Charlie J.,3,"February 23, 2026","Decent, but a bit mixed for me. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for taking the edge off in the evening. One small thing - packaging could be better sealed. At around $19.99, I think it's fairly priced for a gummy of this quality. Fine for the price, wouldn't go out of my way for it though."
TBZ-0013,Barney's Botanicals 12mg Delta 9 Gummies 10ct,Farid O.,5,"April 2, 2026","Couldn't be happier with this purchase. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Great for winding down after work. At around $19.99, I think it's fairly priced for a gummy of this quality. Will be back for more."
TBZ-0013,Barney's Botanicals 12mg Delta 9 Gummies 10ct,Amara J.,4,"March 12, 2026","Solid pick overall, just a couple small notes. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for a mellow weekend afternoon. Grabbed this at the TwoBudz Flower Mound location on a recommendation from a staff member. At around $19.99, I think it's fairly priced for a gummy of this quality. Worth it even with the small downside."
TBZ-0013,Barney's Botanicals 12mg Delta 9 Gummies 10ct,Dario,3,"June 28, 2026","Middle-of-the-road experience, some pros and cons. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. A nice option for easing into sleep. One small thing - wish the flavor was a little stronger. At around $19.99, I think it's fairly priced for a gummy of this quality. Might try a different flavor or size next time."
TBZ-0014,Proleve CBD 2000 Warming Roll On,Owen Ortiz,5,"January 21, 2026","Honestly one of my favorite finds at this store. Applies smoothly and absorbs quickly without leaving a greasy residue behind. Good for sore muscles after a workout. At around $39.99, I think it's fairly priced for a topical of this quality. Great value for the price."
TBZ-0014,Proleve CBD 2000 Warming Roll On,Vance Jensen,5,"June 14, 2026","Better than I expected. Applies smoothly and absorbs quickly without leaving a greasy residue behind. Good for tension after a long day on my feet. At around $39.99, I think it's fairly priced for a topical of this quality. This earned a permanent spot on my shopping list."
TBZ-0014,Proleve CBD 2000 Warming Roll On,Peyton Ellison,5,"May 8, 2026","This quickly became my go-to. Applies smoothly and absorbs quickly without leaving a greasy residue behind. Good for tension after a long day on my feet. At around $39.99, I think it's fairly priced for a topical of this quality. Great value for the price."
TBZ-0014,Proleve CBD 2000 Warming Roll On,Zion,5,"July 15, 2026","Really happy with this one. Applies smoothly and absorbs quickly without leaving a greasy residue behind. Good for tension after a long day on my feet. Found it during a visit to the Flower Mound shop and it's been in my rotation since. At around $39.99, I think it's fairly priced for a topical of this quality. Can't recommend it enough."
TBZ-0014,Proleve CBD 2000 Warming Roll On,Avery Quinn,5,"July 11, 2026","Really happy with this one. Applies smoothly and absorbs quickly without leaving a greasy residue behind. Part of my post-workout recovery routine. At around $39.99, I think it's fairly priced for a topical of this quality. Already recommended it to a friend."
TBZ-0015,Road Trip Desert Stardust Mushroom Chocolate Bar - Strawberry Crunch,Wren Ferrell,4,"March 4, 2026","Glad I tried it - a few minor things keep it from a perfect score. The Strawberry Crunch flavor comes through clearly and it's a fun, discreet snack to have on hand. A fun discreet snack for road trips. Found it during a visit to the Flower Mound shop and it's been in my rotation since. At around $24.99, I think it's fairly priced for a edible of this quality. Would still buy again."
TBZ-0015,Road Trip Desert Stardust Mushroom Chocolate Bar - Strawberry Crunch,Taylor H.,5,"July 4, 2026","This has become a regular pickup for me. The Strawberry Crunch flavor comes through clearly and it's a fun, discreet snack to have on hand. Works well as an easy on-the-go option. At around $24.99, I think it's fairly priced for a edible of this quality. Will be back for more."
TBZ-0015,Road Trip Desert Stardust Mushroom Chocolate Bar - Strawberry Crunch,Jules X.,3,"March 11, 2026","It's fine - does the job, nothing exceptional. The Strawberry Crunch flavor comes through clearly and it's a fun, discreet snack to have on hand. Good for a low-key evening treat. One small thing - the size felt a little small for the price. At around $24.99, I think it's fairly priced for a edible of this quality. Might try a different flavor or size next time."
TBZ-0015,Road Trip Desert Stardust Mushroom Chocolate Bar - Strawberry Crunch,Wren V.,5,"February 23, 2026","This has become a regular pickup for me. The Strawberry Crunch flavor comes through clearly and it's a fun, discreet snack to have on hand. A fun discreet snack for road trips. At around $24.99, I think it's fairly priced for a edible of this quality. Great value for the price."
TBZ-0015,Road Trip Desert Stardust Mushroom Chocolate Bar - Strawberry Crunch,Talia L.,5,"June 6, 2026","Honestly one of my favorite finds at this store. The Strawberry Crunch flavor comes through clearly and it's a fun, discreet snack to have on hand. Works well as an easy on-the-go option. At around $24.99, I think it's fairly priced for a edible of this quality. Can't recommend it enough."
TBZ-0016,Drink Delta D9 Water - Maui Wowie Passion Fruit 20mg,Jordan F.,4,"May 22, 2026","Really good, though not quite perfect. The Maui Wowie Passion Fruit flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. An easy swap for beer at a barbecue. At around $6.99, I think it's fairly priced for a drink of this quality. Minor gripes aside, I'd repurchase."
TBZ-0016,Drink Delta D9 Water - Maui Wowie Passion Fruit 20mg,Brennan Brooks,3,"February 14, 2026","Decent, but a bit mixed for me. The Maui Wowie Passion Fruit flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. A solid alcohol-free option for get-togethers. One small thing - wish the flavor was a little stronger. At around $6.99, I think it's fairly priced for a drink of this quality. Fine for the price, wouldn't go out of my way for it though."
TBZ-0016,Drink Delta D9 Water - Maui Wowie Passion Fruit 20mg,Jonah Monroe,5,"January 3, 2026","This has become a regular pickup for me. The Maui Wowie Passion Fruit flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Works well as a light social drink. Picked it up at the Flower Mound store and the staff pointed me toward it - glad they did. At around $6.99, I think it's fairly priced for a drink of this quality. Will be back for more."
TBZ-0016,Drink Delta D9 Water - Maui Wowie Passion Fruit 20mg,Micah Monroe,5,"January 6, 2026","Better than I expected. The Maui Wowie Passion Fruit flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. An easy swap for beer at a barbecue. Picked it up at the Flower Mound store and the staff pointed me toward it - glad they did. At around $6.99, I think it's fairly priced for a drink of this quality. Already recommended it to a friend."
TBZ-0016,Drink Delta D9 Water - Maui Wowie Passion Fruit 20mg,Skylar Sutton,4,"July 24, 2026","Glad I tried it - a few minor things keep it from a perfect score. The Maui Wowie Passion Fruit flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. A solid alcohol-free option for get-togethers. At around $6.99, I think it's fairly priced for a drink of this quality. Minor gripes aside, I'd repurchase."
TBZ-0017,Drink Delta D9 Water - Wedding Cake Blood Orange 20mg,Yael L.,5,"May 1, 2026","This is now a staple in my rotation. The Wedding Cake Blood Orange flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Good for a relaxed evening without the hangover. At around $6.99, I think it's fairly priced for a drink of this quality. Worth every penny."
TBZ-0017,Drink Delta D9 Water - Wedding Cake Blood Orange 20mg,Phoenix Q.,5,"July 15, 2026","This is now a staple in my rotation. The Wedding Cake Blood Orange flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Nice alternative to a cocktail on a night out. At around $6.99, I think it's fairly priced for a drink of this quality. Already recommended it to a friend."
TBZ-0017,Drink Delta D9 Water - Wedding Cake Blood Orange 20mg,Nadia Ferrell,4,"January 8, 2026","Solid pick overall, just a couple small notes. The Wedding Cake Blood Orange flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. A solid alcohol-free option for get-togethers. At around $6.99, I think it's fairly priced for a drink of this quality. Worth it even with the small downside."
TBZ-0017,Drink Delta D9 Water - Wedding Cake Blood Orange 20mg,Reese B.,5,"January 5, 2026","Impressed from the first time I tried it. The Wedding Cake Blood Orange flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Works well as a light social drink. At around $6.99, I think it's fairly priced for a drink of this quality. Already recommended it to a friend."
TBZ-0017,Drink Delta D9 Water - Wedding Cake Blood Orange 20mg,Drew,5,"April 8, 2026","This quickly became my go-to. The Wedding Cake Blood Orange flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. An easy swap for beer at a barbecue. At around $6.99, I think it's fairly priced for a drink of this quality. Can't recommend it enough."
TBZ-0018,Enjoy Live Rosin Chill Delta 9 Gummies 600mg,Kendall Z.,5,"April 10, 2026","Really happy with this one. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for a mellow weekend afternoon. Found it during a visit to the Flower Mound shop and it's been in my rotation since. At around $74.99, I think it's fairly priced for a gummy of this quality. Worth every penny."
TBZ-0018,Enjoy Live Rosin Chill Delta 9 Gummies 600mg,Jonah F.,5,"January 15, 2026","This has become a regular pickup for me. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Helps me relax without feeling knocked out. At around $74.99, I think it's fairly priced for a gummy of this quality. Will be back for more."
TBZ-0018,Enjoy Live Rosin Chill Delta 9 Gummies 600mg,Sawyer Kessler,5,"March 19, 2026","Impressed from the first time I tried it. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Helps me relax without feeling knocked out. At around $74.99, I think it's fairly priced for a gummy of this quality. Can't recommend it enough."
TBZ-0018,Enjoy Live Rosin Chill Delta 9 Gummies 600mg,Zion Diaz,4,"January 21, 2026","Good experience overall with one small nitpick. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for taking the edge off in the evening. At around $74.99, I think it's fairly priced for a gummy of this quality. Minor gripes aside, I'd repurchase."
TBZ-0018,Enjoy Live Rosin Chill Delta 9 Gummies 600mg,Zion S.,5,"July 27, 2026","Exactly what I was looking for. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Great for winding down after work. At around $74.99, I think it's fairly priced for a gummy of this quality. Can't recommend it enough."
TBZ-0019,Enjoy Live Rosin Delta 9 + CBD Gummies Balance 25ct,Emerson,5,"April 5, 2026","Really happy with this one. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Helps me relax without feeling knocked out. At around $54.99, I think it's fairly priced for a gummy of this quality. Will be back for more."
TBZ-0019,Enjoy Live Rosin Delta 9 + CBD Gummies Balance 25ct,Wren D.,4,"February 18, 2026","Good experience overall with one small nitpick. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Great for winding down after work. At around $54.99, I think it's fairly priced for a gummy of this quality. Worth it even with the small downside."
TBZ-0019,Enjoy Live Rosin Delta 9 + CBD Gummies Balance 25ct,Riley Hayes,5,"February 2, 2026","Honestly one of my favorite finds at this store. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Helps me relax without feeling knocked out. At around $54.99, I think it's fairly priced for a gummy of this quality. Already recommended it to a friend."
TBZ-0019,Enjoy Live Rosin Delta 9 + CBD Gummies Balance 25ct,Tatum Kessler,5,"June 26, 2026","Honestly one of my favorite finds at this store. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. A nice option for easing into sleep. At around $54.99, I think it's fairly priced for a gummy of this quality. Already recommended it to a friend."
TBZ-0019,Enjoy Live Rosin Delta 9 + CBD Gummies Balance 25ct,Skylar Griffin,4,"January 18, 2026","Good experience overall with one small nitpick. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for taking the edge off in the evening. At around $54.99, I think it's fairly priced for a gummy of this quality. Worth it even with the small downside."
TBZ-0020,Wyld CBD Sparkling Water - Grapefruit 20mg CBD + 10mg CBG,Vance,4,"February 5, 2026","Really good, though not quite perfect. The Grapefruit  CBD +  CBG flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Works well as a light social drink. At around $5.99, I think it's fairly priced for a drink of this quality. Would still buy again."
TBZ-0020,Wyld CBD Sparkling Water - Grapefruit 20mg CBD + 10mg CBG,Dario N.,5,"July 1, 2026","This has become a regular pickup for me. The Grapefruit  CBD +  CBG flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Good option when i want to skip alcohol but still unwind. At around $5.99, I think it's fairly priced for a drink of this quality. Already recommended it to a friend."
TBZ-0020,Wyld CBD Sparkling Water - Grapefruit 20mg CBD + 10mg CBG,Emery Quinn,5,"April 28, 2026","Really happy with this one. The Grapefruit  CBD +  CBG flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Nice alternative to a cocktail on a night out. At around $5.99, I think it's fairly priced for a drink of this quality. Worth every penny."
TBZ-0020,Wyld CBD Sparkling Water - Grapefruit 20mg CBD + 10mg CBG,Jesse F.,3,"February 9, 2026","It's fine - does the job, nothing exceptional. The Grapefruit  CBD +  CBG flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. An easy swap for beer at a barbecue. One small thing - the size felt a little small for the price. At around $5.99, I think it's fairly priced for a drink of this quality. Fine for the price, wouldn't go out of my way for it though."
TBZ-0020,Wyld CBD Sparkling Water - Grapefruit 20mg CBD + 10mg CBG,Owen,5,"July 2, 2026","Honestly one of my favorite finds at this store. The Grapefruit  CBD +  CBG flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Good option when i want to skip alcohol but still unwind. At around $5.99, I think it's fairly priced for a drink of this quality. Great value for the price."
TBZ-0021,Enjoy Live Rosin Delta 9 Gummies 300mg - Bliss,Ines Y.,5,"May 27, 2026","Honestly one of my favorite finds at this store. The Bliss flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. A nice option for easing into sleep. At around $44.99, I think it's fairly priced for a gummy of this quality. Already recommended it to a friend."
TBZ-0021,Enjoy Live Rosin Delta 9 Gummies 300mg - Bliss,Vic,5,"June 5, 2026","This is now a staple in my rotation. The Bliss flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Helps me relax without feeling knocked out. At around $44.99, I think it's fairly priced for a gummy of this quality. Would buy again."
TBZ-0021,Enjoy Live Rosin Delta 9 Gummies 300mg - Bliss,Cameron Carter,4,"February 25, 2026","Good experience overall with one small nitpick. The Bliss flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Works well as a low-key nighttime routine. At around $44.99, I think it's fairly priced for a gummy of this quality. Solid enough that I'll grab it again."
TBZ-0021,Enjoy Live Rosin Delta 9 Gummies 300mg - Bliss,Kit Reyes,5,"June 6, 2026","Impressed from the first time I tried it. The Bliss flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. A nice option for easing into sleep. At around $44.99, I think it's fairly priced for a gummy of this quality. This earned a permanent spot on my shopping list."
TBZ-0021,Enjoy Live Rosin Delta 9 Gummies 300mg - Bliss,Ines M.,5,"February 13, 2026","Didn't expect to like this as much as I do. The Bliss flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Good for a mellow weekend afternoon. At around $44.99, I think it's fairly priced for a gummy of this quality. Would buy again."
TBZ-0022,Enjoy Live Rosin Delta 9 Gummies Euphoria 25ct,Emery H.,4,"March 12, 2026","Solid pick overall, just a couple small notes. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for taking the edge off in the evening. At around $44.99, I think it's fairly priced for a gummy of this quality. Minor gripes aside, I'd repurchase."
TBZ-0022,Enjoy Live Rosin Delta 9 Gummies Euphoria 25ct,Sawyer O.,5,"March 14, 2026","Didn't expect to like this as much as I do. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Great for winding down after work. At around $44.99, I think it's fairly priced for a gummy of this quality. Already recommended it to a friend."
TBZ-0022,Enjoy Live Rosin Delta 9 Gummies Euphoria 25ct,Sage,5,"June 20, 2026","Couldn't be happier with this purchase. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for a mellow weekend afternoon. At around $44.99, I think it's fairly priced for a gummy of this quality. Can't recommend it enough."
TBZ-0022,Enjoy Live Rosin Delta 9 Gummies Euphoria 25ct,Jordan,3,"July 12, 2026","Decent, but a bit mixed for me. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Great for winding down after work. One small thing - packaging could be better sealed. At around $44.99, I think it's fairly priced for a gummy of this quality. Might try a different flavor or size next time."
TBZ-0022,Enjoy Live Rosin Delta 9 Gummies Euphoria 25ct,Cameron,5,"March 11, 2026","This quickly became my go-to. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Great for winding down after work. The Flower Mound TwoBudz team recommended this one and it didn't disappoint. At around $44.99, I think it's fairly priced for a gummy of this quality. Would buy again."
TBZ-0023,Hometown Hero Delta 9 Cocoa Crisp Cereal Bites,Vic V.,5,"February 3, 2026","Exactly what I was looking for. It's a fun, discreet snack to have on hand and the flavor comes through clearly. Works well as an easy on-the-go option. At around $49.99, I think it's fairly priced for a edible of this quality. Worth every penny."
TBZ-0023,Hometown Hero Delta 9 Cocoa Crisp Cereal Bites,Gale J.,4,"June 8, 2026","Really good, though not quite perfect. It's a fun, discreet snack to have on hand and the flavor comes through clearly. Works well as an easy on-the-go option. At around $49.99, I think it's fairly priced for a edible of this quality. Worth it even with the small downside."
TBZ-0023,Hometown Hero Delta 9 Cocoa Crisp Cereal Bites,Alex Vance,4,"May 15, 2026","Good experience overall with one small nitpick. It's a fun, discreet snack to have on hand and the flavor comes through clearly. Works well as an easy on-the-go option. Found it during a visit to the Flower Mound shop and it's been in my rotation since. At around $49.99, I think it's fairly priced for a edible of this quality. Worth it even with the small downside."
TBZ-0023,Hometown Hero Delta 9 Cocoa Crisp Cereal Bites,Hollis,5,"June 24, 2026","Impressed from the first time I tried it. It's a fun, discreet snack to have on hand and the flavor comes through clearly. Good for a low-key evening treat. At around $49.99, I think it's fairly priced for a edible of this quality. Can't recommend it enough."
TBZ-0023,Hometown Hero Delta 9 Cocoa Crisp Cereal Bites,Ellis R.,4,"April 18, 2026","Solid pick overall, just a couple small notes. It's a fun, discreet snack to have on hand and the flavor comes through clearly. A fun discreet snack for road trips. At around $49.99, I think it's fairly priced for a edible of this quality. Would still buy again."
TBZ-0024,Wyld CBD Sparkling Water - Blackberry 50mg CBD,Morgan,5,"March 23, 2026","Impressed from the first time I tried it. The Blackberry  CBD flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Works well as a light social drink. At around $5.99, I think it's fairly priced for a drink of this quality. Great value for the price."
TBZ-0024,Wyld CBD Sparkling Water - Blackberry 50mg CBD,Jonah R.,5,"April 7, 2026","Impressed from the first time I tried it. The Blackberry  CBD flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Good option when i want to skip alcohol but still unwind. At around $5.99, I think it's fairly priced for a drink of this quality. Would buy again."
TBZ-0024,Wyld CBD Sparkling Water - Blackberry 50mg CBD,Jules K.,5,"April 13, 2026","Honestly one of my favorite finds at this store. The Blackberry  CBD flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Good for a relaxed evening without the hangover. At around $5.99, I think it's fairly priced for a drink of this quality. Will be back for more."
TBZ-0024,Wyld CBD Sparkling Water - Blackberry 50mg CBD,Taylor P.,3,"January 16, 2026","Decent, but a bit mixed for me. The Blackberry  CBD flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. A solid alcohol-free option for get-togethers. One small thing - flavor was a bit more muted than I hoped. At around $5.99, I think it's fairly priced for a drink of this quality. Not bad, but I'll probably look at other options too."
TBZ-0024,Wyld CBD Sparkling Water - Blackberry 50mg CBD,Dallas Dunham,5,"July 22, 2026","Better than I expected. The Blackberry  CBD flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Works well as a light social drink. At around $5.99, I think it's fairly priced for a drink of this quality. This earned a permanent spot on my shopping list."
TBZ-0025,"Proleve - CBD Daily Gummies - 1500mg, 30 Count",Elliot Lambert,5,"July 11, 2026","Didn't expect to like this as much as I do. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for taking the edge off in the evening. At around $64.99, I think it's fairly priced for a gummy of this quality. Can't recommend it enough."
TBZ-0025,"Proleve - CBD Daily Gummies - 1500mg, 30 Count",Lior Underwood,4,"March 7, 2026","Really good, though not quite perfect. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for taking the edge off in the evening. At around $64.99, I think it's fairly priced for a gummy of this quality. Minor gripes aside, I'd repurchase."
TBZ-0025,"Proleve - CBD Daily Gummies - 1500mg, 30 Count",Reagan T.,5,"May 17, 2026","Better than I expected. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Great for winding down after work. At around $64.99, I think it's fairly priced for a gummy of this quality. Would buy again."
TBZ-0025,"Proleve - CBD Daily Gummies - 1500mg, 30 Count",Wes M.,5,"July 21, 2026","Couldn't be happier with this purchase. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Works well as a low-key nighttime routine. At around $64.99, I think it's fairly priced for a gummy of this quality. Will be back for more."
TBZ-0025,"Proleve - CBD Daily Gummies - 1500mg, 30 Count",Yusuf,5,"June 26, 2026","Didn't expect to like this as much as I do. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. A nice option for easing into sleep. At around $64.99, I think it's fairly priced for a gummy of this quality. Will be back for more."
TBZ-0026,Wyld CBD Sparkling Water - Blood Orange 50mg,Shawn Carter,5,"April 24, 2026","Honestly one of my favorite finds at this store. The Blood Orange flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. An easy swap for beer at a barbecue. At around $5.99, I think it's fairly priced for a drink of this quality. Will be back for more."
TBZ-0026,Wyld CBD Sparkling Water - Blood Orange 50mg,Xan,3,"January 6, 2026","It's fine - does the job, nothing exceptional. The Blood Orange flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Works well as a light social drink. The Flower Mound TwoBudz team recommended this one and it didn't disappoint. One small thing - took longer than I expected to feel anything. At around $5.99, I think it's fairly priced for a drink of this quality. Not bad, but I'll probably look at other options too."
TBZ-0026,Wyld CBD Sparkling Water - Blood Orange 50mg,Jae,4,"July 12, 2026","Good experience overall with one small nitpick. The Blood Orange flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Nice alternative to a cocktail on a night out. Grabbed this at the TwoBudz Flower Mound location on a recommendation from a staff member. At around $5.99, I think it's fairly priced for a drink of this quality. Minor gripes aside, I'd repurchase."
TBZ-0026,Wyld CBD Sparkling Water - Blood Orange 50mg,Lior Alcott,5,"March 14, 2026","Better than I expected. The Blood Orange flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Good option when i want to skip alcohol but still unwind. At around $5.99, I think it's fairly priced for a drink of this quality. This earned a permanent spot on my shopping list."
TBZ-0026,Wyld CBD Sparkling Water - Blood Orange 50mg,Brennan M.,3,"January 12, 2026","It's fine - does the job, nothing exceptional. The Blood Orange flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. An easy swap for beer at a barbecue. One small thing - packaging could be better sealed. At around $5.99, I think it's fairly priced for a drink of this quality. Fine for the price, wouldn't go out of my way for it though."
TBZ-0027,Barney's Botanicals 30mg Delta 9 Gummies 30ct,Soren Reyes,5,"January 23, 2026","Impressed from the first time I tried it. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Works well as a low-key nighttime routine. At around $74.99, I think it's fairly priced for a gummy of this quality. Worth every penny."
TBZ-0027,Barney's Botanicals 30mg Delta 9 Gummies 30ct,Soren Monroe,5,"May 7, 2026","Really happy with this one. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for taking the edge off in the evening. At around $74.99, I think it's fairly priced for a gummy of this quality. Great value for the price."
TBZ-0027,Barney's Botanicals 30mg Delta 9 Gummies 30ct,Skylar R.,4,"March 26, 2026","Good experience overall with one small nitpick. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for a mellow weekend afternoon. At around $74.99, I think it's fairly priced for a gummy of this quality. Solid enough that I'll grab it again."
TBZ-0027,Barney's Botanicals 30mg Delta 9 Gummies 30ct,Esme Young,4,"February 2, 2026","Glad I tried it - a few minor things keep it from a perfect score. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for a mellow weekend afternoon. At around $74.99, I think it's fairly priced for a gummy of this quality. Solid enough that I'll grab it again."
TBZ-0027,Barney's Botanicals 30mg Delta 9 Gummies 30ct,Val E.,3,"March 16, 2026","It's fine - does the job, nothing exceptional. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for a mellow weekend afternoon. One small thing - wish the flavor was a little stronger. At around $74.99, I think it's fairly priced for a gummy of this quality. Worth trying once to see if it's for you."
TBZ-0028,Hometown Hero Delta 9 Live Rosin Gummies Grand Daddy Purple 10ct,Dakota J.,5,"February 17, 2026","Exactly what I was looking for. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Great for winding down after work. At around $69.99, I think it's fairly priced for a gummy of this quality. Great value for the price."
TBZ-0028,Hometown Hero Delta 9 Live Rosin Gummies Grand Daddy Purple 10ct,Talia O.,5,"July 11, 2026","Really happy with this one. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Great for winding down after work. At around $69.99, I think it's fairly priced for a gummy of this quality. Already recommended it to a friend."
TBZ-0028,Hometown Hero Delta 9 Live Rosin Gummies Grand Daddy Purple 10ct,Riley Brooks,4,"February 9, 2026","Good experience overall with one small nitpick. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. A nice option for easing into sleep. At around $69.99, I think it's fairly priced for a gummy of this quality. Minor gripes aside, I'd repurchase."
TBZ-0028,Hometown Hero Delta 9 Live Rosin Gummies Grand Daddy Purple 10ct,Peyton,5,"April 25, 2026","Exactly what I was looking for. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Helps me relax without feeling knocked out. At around $69.99, I think it's fairly priced for a gummy of this quality. Would buy again."
TBZ-0028,Hometown Hero Delta 9 Live Rosin Gummies Grand Daddy Purple 10ct,Reese Brooks,4,"April 2, 2026","Good experience overall with one small nitpick. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Great for winding down after work. At around $69.99, I think it's fairly priced for a gummy of this quality. Worth it even with the small downside."
TBZ-0029,CBD/CBN Gummies 3300mg - Sleep,Charlie E.,5,"April 16, 2026","This quickly became my go-to. The Sleep flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Good for taking the edge off in the evening. At around $79.99, I think it's fairly priced for a gummy of this quality. Worth every penny."
TBZ-0029,CBD/CBN Gummies 3300mg - Sleep,Ira Alcott,5,"July 9, 2026","Better than I expected. The Sleep flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Good for taking the edge off in the evening. At around $79.99, I think it's fairly priced for a gummy of this quality. Will be back for more."
TBZ-0029,CBD/CBN Gummies 3300mg - Sleep,Yusuf M.,3,"March 15, 2026","It's fine - does the job, nothing exceptional. The Sleep flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Works well as a low-key nighttime routine. One small thing - wish the flavor was a little stronger. At around $79.99, I think it's fairly priced for a gummy of this quality. Might try a different flavor or size next time."
TBZ-0029,CBD/CBN Gummies 3300mg - Sleep,Ines V.,4,"July 11, 2026","Solid pick overall, just a couple small notes. The Sleep flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Good for taking the edge off in the evening. The Flower Mound TwoBudz team recommended this one and it didn't disappoint. At around $79.99, I think it's fairly priced for a gummy of this quality. Worth it even with the small downside."
TBZ-0029,CBD/CBN Gummies 3300mg - Sleep,Indigo Ibarra,5,"March 16, 2026","This quickly became my go-to. The Sleep flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. A nice option for easing into sleep. Picked it up at the Flower Mound store and the staff pointed me toward it - glad they did. At around $79.99, I think it's fairly priced for a gummy of this quality. This earned a permanent spot on my shopping list."
TBZ-0030,Hometown Hero Delta 9 Live Rosin Gummies Blue Dream 10ct,Cleo Dunham,5,"May 19, 2026","Honestly one of my favorite finds at this store. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. A nice option for easing into sleep. At around $69.99, I think it's fairly priced for a gummy of this quality. Worth every penny."
TBZ-0030,Hometown Hero Delta 9 Live Rosin Gummies Blue Dream 10ct,Sage J.,5,"June 8, 2026","This quickly became my go-to. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for a mellow weekend afternoon. Picked it up at the Flower Mound store and the staff pointed me toward it - glad they did. At around $69.99, I think it's fairly priced for a gummy of this quality. Would buy again."
TBZ-0030,Hometown Hero Delta 9 Live Rosin Gummies Blue Dream 10ct,Hollis Quinn,4,"January 26, 2026","Good experience overall with one small nitpick. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Helps me relax without feeling knocked out. At around $69.99, I think it's fairly priced for a gummy of this quality. Minor gripes aside, I'd repurchase."
TBZ-0030,Hometown Hero Delta 9 Live Rosin Gummies Blue Dream 10ct,Amara Young,3,"March 20, 2026","Middle-of-the-road experience, some pros and cons. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for a mellow weekend afternoon. One small thing - packaging could be better sealed. At around $69.99, I think it's fairly priced for a gummy of this quality. Worth trying once to see if it's for you."
TBZ-0030,Hometown Hero Delta 9 Live Rosin Gummies Blue Dream 10ct,Charlie Q.,4,"June 20, 2026","Good experience overall with one small nitpick. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for taking the edge off in the evening. At around $69.99, I think it's fairly priced for a gummy of this quality. Worth it even with the small downside."
TBZ-0031,Enjoy CBD/CBG Gummies 3300mg - Relief,Wes,5,"April 6, 2026","Exactly what I was looking for. The Relief flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Great for winding down after work. At around $69.99, I think it's fairly priced for a gummy of this quality. Can't recommend it enough."
TBZ-0031,Enjoy CBD/CBG Gummies 3300mg - Relief,Amara Reyes,3,"June 7, 2026","It's fine - does the job, nothing exceptional. The Relief flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Helps me relax without feeling knocked out. One small thing - the size felt a little small for the price. At around $69.99, I think it's fairly priced for a gummy of this quality. Not bad, but I'll probably look at other options too."
TBZ-0031,Enjoy CBD/CBG Gummies 3300mg - Relief,Lior Walsh,3,"April 2, 2026","Middle-of-the-road experience, some pros and cons. The Relief flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Great for winding down after work. One small thing - the size felt a little small for the price. At around $69.99, I think it's fairly priced for a gummy of this quality. Not bad, but I'll probably look at other options too."
TBZ-0031,Enjoy CBD/CBG Gummies 3300mg - Relief,Rhys Brooks,5,"February 7, 2026","This is now a staple in my rotation. The Relief flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Good for a mellow weekend afternoon. At around $69.99, I think it's fairly priced for a gummy of this quality. Great value for the price."
TBZ-0031,Enjoy CBD/CBG Gummies 3300mg - Relief,Brennan K.,4,"January 23, 2026","Glad I tried it - a few minor things keep it from a perfect score. The Relief flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Helps me relax without feeling knocked out. At around $69.99, I think it's fairly priced for a gummy of this quality. Would still buy again."
TBZ-0032,Hometown Hero Delta 9 Fruity Rainbow Cereal Bites,Ursula Q.,5,"July 20, 2026","Couldn't be happier with this purchase. It's a fun, discreet snack to have on hand and the flavor comes through clearly. Works well as an easy on-the-go option. Picked it up at the Flower Mound store and the staff pointed me toward it - glad they did. At around $49.99, I think it's fairly priced for a edible of this quality. Great value for the price."
TBZ-0032,Hometown Hero Delta 9 Fruity Rainbow Cereal Bites,Corey S.,5,"March 19, 2026","This is now a staple in my rotation. It's a fun, discreet snack to have on hand and the flavor comes through clearly. A fun discreet snack for road trips. At around $49.99, I think it's fairly priced for a edible of this quality. Great value for the price."
TBZ-0032,Hometown Hero Delta 9 Fruity Rainbow Cereal Bites,Phoenix N.,5,"July 17, 2026","Exactly what I was looking for. It's a fun, discreet snack to have on hand and the flavor comes through clearly. Works well as an easy on-the-go option. Grabbed this at the TwoBudz Flower Mound location on a recommendation from a staff member. At around $49.99, I think it's fairly priced for a edible of this quality. Would buy again."
TBZ-0032,Hometown Hero Delta 9 Fruity Rainbow Cereal Bites,Priya D.,5,"April 16, 2026","This quickly became my go-to. It's a fun, discreet snack to have on hand and the flavor comes through clearly. Works well as an easy on-the-go option. At around $49.99, I think it's fairly priced for a edible of this quality. Great value for the price."
TBZ-0032,Hometown Hero Delta 9 Fruity Rainbow Cereal Bites,Jules,5,"June 8, 2026","Better than I expected. It's a fun, discreet snack to have on hand and the flavor comes through clearly. A nice discreet alternative to smoking. The Flower Mound TwoBudz team recommended this one and it didn't disappoint. At around $49.99, I think it's fairly priced for a edible of this quality. Already recommended it to a friend."
TBZ-0033,Hometown Hero Delta 9 Live Rosin Gummies Gelato 10ct,Zion V.,5,"April 10, 2026","Didn't expect to like this as much as I do. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. A nice option for easing into sleep. At around $69.99, I think it's fairly priced for a gummy of this quality. Can't recommend it enough."
TBZ-0033,Hometown Hero Delta 9 Live Rosin Gummies Gelato 10ct,Noel K.,5,"February 21, 2026","Impressed from the first time I tried it. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Works well as a low-key nighttime routine. Found it during a visit to the Flower Mound shop and it's been in my rotation since. At around $69.99, I think it's fairly priced for a gummy of this quality. Worth every penny."
TBZ-0033,Hometown Hero Delta 9 Live Rosin Gummies Gelato 10ct,Val Turner,5,"July 11, 2026","Impressed from the first time I tried it. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Works well as a low-key nighttime routine. At around $69.99, I think it's fairly priced for a gummy of this quality. Will be back for more."
TBZ-0033,Hometown Hero Delta 9 Live Rosin Gummies Gelato 10ct,Devon Ellison,5,"March 7, 2026","Honestly one of my favorite finds at this store. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for a mellow weekend afternoon. At around $69.99, I think it's fairly priced for a gummy of this quality. Great value for the price."
TBZ-0033,Hometown Hero Delta 9 Live Rosin Gummies Gelato 10ct,Zion Diaz,5,"February 15, 2026","Honestly one of my favorite finds at this store. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. A nice option for easing into sleep. Found it during a visit to the Flower Mound shop and it's been in my rotation since. At around $69.99, I think it's fairly priced for a gummy of this quality. Already recommended it to a friend."
TBZ-0034,Enjoy Live Rosin Euphoria Delta 9 Gummies 600mg,Mika Alcott,4,"July 19, 2026","Glad I tried it - a few minor things keep it from a perfect score. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for a mellow weekend afternoon. At around $74.99, I think it's fairly priced for a gummy of this quality. Worth it even with the small downside."
TBZ-0034,Enjoy Live Rosin Euphoria Delta 9 Gummies 600mg,Priya Vance,5,"February 3, 2026","Exactly what I was looking for. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. A nice option for easing into sleep. At around $74.99, I think it's fairly priced for a gummy of this quality. Great value for the price."
TBZ-0034,Enjoy Live Rosin Euphoria Delta 9 Gummies 600mg,Rhys Ortiz,5,"April 25, 2026","Really happy with this one. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Works well as a low-key nighttime routine. At around $74.99, I think it's fairly priced for a gummy of this quality. Would buy again."
TBZ-0034,Enjoy Live Rosin Euphoria Delta 9 Gummies 600mg,Sam Ibarra,5,"June 14, 2026","Couldn't be happier with this purchase. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Helps me relax without feeling knocked out. At around $74.99, I think it's fairly priced for a gummy of this quality. Will be back for more."
TBZ-0034,Enjoy Live Rosin Euphoria Delta 9 Gummies 600mg,Cleo Ibarra,4,"April 2, 2026","Good experience overall with one small nitpick. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Helps me relax without feeling knocked out. At around $74.99, I think it's fairly priced for a gummy of this quality. Worth it even with the small downside."
TBZ-0035,"Proleve - CBD Night Gummies - 50mg, 30 Count",Dario Ferrell,5,"April 8, 2026","Exactly what I was looking for. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Great for winding down after work. At around $64.99, I think it's fairly priced for a gummy of this quality. Will be back for more."
TBZ-0035,"Proleve - CBD Night Gummies - 50mg, 30 Count",Parker L.,4,"January 17, 2026","Glad I tried it - a few minor things keep it from a perfect score. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Works well as a low-key nighttime routine. At around $64.99, I think it's fairly priced for a gummy of this quality. Worth it even with the small downside."
TBZ-0035,"Proleve - CBD Night Gummies - 50mg, 30 Count",Amara U.,5,"April 11, 2026","Exactly what I was looking for. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Helps me relax without feeling knocked out. At around $64.99, I think it's fairly priced for a gummy of this quality. Great value for the price."
TBZ-0035,"Proleve - CBD Night Gummies - 50mg, 30 Count",Devon Reyes,5,"March 28, 2026","Better than I expected. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for a mellow weekend afternoon. At around $64.99, I think it's fairly priced for a gummy of this quality. Would buy again."
TBZ-0035,"Proleve - CBD Night Gummies - 50mg, 30 Count",Huxley,4,"February 4, 2026","Really good, though not quite perfect. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. A nice option for easing into sleep. Grabbed this at the TwoBudz Flower Mound location on a recommendation from a staff member. At around $64.99, I think it's fairly priced for a gummy of this quality. Worth it even with the small downside."
TBZ-0036,Wintergreen THC Microdose Mints - 40 Count,Yusuf Xu,4,"June 6, 2026","Really good, though not quite perfect. It's a fun, discreet snack to have on hand and the flavor comes through clearly. Works well as an easy on-the-go option. Grabbed this at the TwoBudz Flower Mound location on a recommendation from a staff member. At around $17.99, I think it's fairly priced for a edible of this quality. Minor gripes aside, I'd repurchase."
TBZ-0036,Wintergreen THC Microdose Mints - 40 Count,Uma L.,5,"January 13, 2026","Didn't expect to like this as much as I do. It's a fun, discreet snack to have on hand and the flavor comes through clearly. Good for a low-key evening treat. At around $17.99, I think it's fairly priced for a edible of this quality. This earned a permanent spot on my shopping list."
TBZ-0036,Wintergreen THC Microdose Mints - 40 Count,Reagan,5,"July 4, 2026","Couldn't be happier with this purchase. It's a fun, discreet snack to have on hand and the flavor comes through clearly. A nice discreet alternative to smoking. At around $17.99, I think it's fairly priced for a edible of this quality. Already recommended it to a friend."
TBZ-0036,Wintergreen THC Microdose Mints - 40 Count,Reese O.,5,"July 11, 2026","Better than I expected. It's a fun, discreet snack to have on hand and the flavor comes through clearly. Good for a low-key evening treat. At around $17.99, I think it's fairly priced for a edible of this quality. Worth every penny."
TBZ-0036,Wintergreen THC Microdose Mints - 40 Count,Vance Reyes,4,"April 8, 2026","Solid pick overall, just a couple small notes. It's a fun, discreet snack to have on hand and the flavor comes through clearly. A nice discreet alternative to smoking. At around $17.99, I think it's fairly priced for a edible of this quality. Worth it even with the small downside."
TBZ-0037,Wyld Blood Orange THC + CBC Gummies - 10ct,Soren Walsh,4,"April 27, 2026","Good experience overall with one small nitpick. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Great for winding down after work. At around $34.99, I think it's fairly priced for a gummy of this quality. Minor gripes aside, I'd repurchase."
TBZ-0037,Wyld Blood Orange THC + CBC Gummies - 10ct,Esme Ferrell,5,"February 25, 2026","Didn't expect to like this as much as I do. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Helps me relax without feeling knocked out. At around $34.99, I think it's fairly priced for a gummy of this quality. This earned a permanent spot on my shopping list."
TBZ-0037,Wyld Blood Orange THC + CBC Gummies - 10ct,Drew I.,4,"March 27, 2026","Solid pick overall, just a couple small notes. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Helps me relax without feeling knocked out. At around $34.99, I think it's fairly priced for a gummy of this quality. Minor gripes aside, I'd repurchase."
TBZ-0037,Wyld Blood Orange THC + CBC Gummies - 10ct,Elliot,5,"May 4, 2026","Impressed from the first time I tried it. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Works well as a low-key nighttime routine. At around $34.99, I think it's fairly priced for a gummy of this quality. Can't recommend it enough."
TBZ-0037,Wyld Blood Orange THC + CBC Gummies - 10ct,Indigo D.,5,"July 27, 2026","Honestly one of my favorite finds at this store. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Helps me relax without feeling knocked out. At around $34.99, I think it's fairly priced for a gummy of this quality. Already recommended it to a friend."
TBZ-0038,Northern Lights Live Rosin THC Gummies - Indica,Morgan Alcott,4,"February 21, 2026","Good experience overall with one small nitpick. The Indica flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. A nice option for easing into sleep. At around $69.99, I think it's fairly priced for a gummy of this quality. Worth it even with the small downside."
TBZ-0038,Northern Lights Live Rosin THC Gummies - Indica,Devon Sutton,5,"February 18, 2026","Better than I expected. The Indica flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Helps me relax without feeling knocked out. The Flower Mound TwoBudz team recommended this one and it didn't disappoint. At around $69.99, I think it's fairly priced for a gummy of this quality. Great value for the price."
TBZ-0038,Northern Lights Live Rosin THC Gummies - Indica,Dario J.,5,"June 13, 2026","Honestly one of my favorite finds at this store. The Indica flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Good for taking the edge off in the evening. At around $69.99, I think it's fairly priced for a gummy of this quality. Worth every penny."
TBZ-0038,Northern Lights Live Rosin THC Gummies - Indica,Ursula Ibarra,4,"July 11, 2026","Solid pick overall, just a couple small notes. The Indica flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Helps me relax without feeling knocked out. At around $69.99, I think it's fairly priced for a gummy of this quality. Worth it even with the small downside."
TBZ-0038,Northern Lights Live Rosin THC Gummies - Indica,Gia Bishop,5,"June 13, 2026","This quickly became my go-to. The Indica flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Good for a mellow weekend afternoon. At around $69.99, I think it's fairly priced for a gummy of this quality. Would buy again."
TBZ-0039,Dark Cherry CBD + CBN + THC Gummies - Sleep Support,Jae Quinn,5,"February 19, 2026","Better than I expected. The Sleep Support flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. A nice option for easing into sleep. At around $59.99, I think it's fairly priced for a gummy of this quality. Already recommended it to a friend."
TBZ-0039,Dark Cherry CBD + CBN + THC Gummies - Sleep Support,Vic Ibarra,3,"March 27, 2026","Middle-of-the-road experience, some pros and cons. The Sleep Support flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. A nice option for easing into sleep. One small thing - flavor was a bit more muted than I hoped. At around $59.99, I think it's fairly priced for a gummy of this quality. Might try a different flavor or size next time."
TBZ-0039,Dark Cherry CBD + CBN + THC Gummies - Sleep Support,Cameron Xu,3,"April 25, 2026","It's fine - does the job, nothing exceptional. The Sleep Support flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Helps me relax without feeling knocked out. One small thing - would like a slightly bigger size option. At around $59.99, I think it's fairly priced for a gummy of this quality. Might try a different flavor or size next time."
TBZ-0039,Dark Cherry CBD + CBN + THC Gummies - Sleep Support,Jae T.,5,"July 1, 2026","Couldn't be happier with this purchase. The Sleep Support flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Works well as a low-key nighttime routine. Found it during a visit to the Flower Mound shop and it's been in my rotation since. At around $59.99, I think it's fairly priced for a gummy of this quality. Can't recommend it enough."
TBZ-0039,Dark Cherry CBD + CBN + THC Gummies - Sleep Support,Jamie U.,4,"January 5, 2026","Good experience overall with one small nitpick. The Sleep Support flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Great for winding down after work. At around $59.99, I think it's fairly priced for a gummy of this quality. Minor gripes aside, I'd repurchase."
TBZ-0040,Wyld Pomegranate THC + CBD Gummies - 10mg,Esme,3,"April 15, 2026","Decent, but a bit mixed for me. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for taking the edge off in the evening. One small thing - the size felt a little small for the price. At around $34.99, I think it's fairly priced for a gummy of this quality. Not bad, but I'll probably look at other options too."
TBZ-0040,Wyld Pomegranate THC + CBD Gummies - 10mg,Kendall B.,5,"January 26, 2026","Exactly what I was looking for. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Helps me relax without feeling knocked out. Picked it up at the Flower Mound store and the staff pointed me toward it - glad they did. At around $34.99, I think it's fairly priced for a gummy of this quality. Great value for the price."
TBZ-0040,Wyld Pomegranate THC + CBD Gummies - 10mg,Finley M.,5,"June 28, 2026","This quickly became my go-to. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Works well as a low-key nighttime routine. At around $34.99, I think it's fairly priced for a gummy of this quality. This earned a permanent spot on my shopping list."
TBZ-0040,Wyld Pomegranate THC + CBD Gummies - 10mg,Skylar F.,3,"March 19, 2026","It's fine - does the job, nothing exceptional. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Helps me relax without feeling knocked out. One small thing - wish the flavor was a little stronger. At around $34.99, I think it's fairly priced for a gummy of this quality. Fine for the price, wouldn't go out of my way for it though."
TBZ-0040,Wyld Pomegranate THC + CBD Gummies - 10mg,Nadia V.,4,"April 21, 2026","Solid pick overall, just a couple small notes. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Great for winding down after work. At around $34.99, I think it's fairly priced for a gummy of this quality. Solid enough that I'll grab it again."
TBZ-0041,Wyld THC-Free Peach CBD Gummies,Amara Anderson,3,"June 12, 2026","It's fine - does the job, nothing exceptional. The Free Peach CBD Gummies flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Good for taking the edge off in the evening. One small thing - would like a slightly bigger size option. At around $64.99, I think it's fairly priced for a gummy of this quality. Worth trying once to see if it's for you."
TBZ-0041,Wyld THC-Free Peach CBD Gummies,Uma G.,5,"June 9, 2026","This is now a staple in my rotation. The Free Peach CBD Gummies flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Good for a mellow weekend afternoon. At around $64.99, I think it's fairly priced for a gummy of this quality. Great value for the price."
TBZ-0041,Wyld THC-Free Peach CBD Gummies,Kai V.,4,"April 5, 2026","Solid pick overall, just a couple small notes. The Free Peach CBD Gummies flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Works well as a low-key nighttime routine. At around $64.99, I think it's fairly priced for a gummy of this quality. Worth it even with the small downside."
TBZ-0041,Wyld THC-Free Peach CBD Gummies,Kai Monroe,5,"January 1, 2026","This is now a staple in my rotation. The Free Peach CBD Gummies flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Good for taking the edge off in the evening. At around $64.99, I think it's fairly priced for a gummy of this quality. Can't recommend it enough."
TBZ-0041,Wyld THC-Free Peach CBD Gummies,Riley H.,5,"May 14, 2026","Couldn't be happier with this purchase. The Free Peach CBD Gummies flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Good for a mellow weekend afternoon. At around $64.99, I think it's fairly priced for a gummy of this quality. Can't recommend it enough."
`;

// Helper: Parse CSV
function parseCSVRows(csvStr) {
  const rows = [];
  let row = [];
  let cell = "";
  let insideQuote = false;

  for (let i = 0; i < csvStr.length; i++) {
    const char = csvStr[i];
    const nextChar = csvStr[i + 1];

    if (char === '"') {
      if (insideQuote && nextChar === '"') {
        cell += '"';
        i++;
      } else {
        insideQuote = !insideQuote;
      }
    } else if (char === "," && !insideQuote) {
      row.push(cell.trim());
      cell = "";
    } else if ((char === "\r" || char === "\n") && !insideQuote) {
      if (char === "\r" && nextChar === "\n") i++;
      row.push(cell.trim());
      if (row.some(c => c.length > 0)) rows.push(row);
      row = [];
      cell = "";
    } else {
      cell += char;
    }
  }
  if (cell || row.length > 0) {
    row.push(cell.trim());
    if (row.some(c => c.length > 0)) rows.push(row);
  }
  return rows;
}

const parsedRows = parseCSVRows(userCsvText.trim());
console.log(`Parsed ${parsedRows.length - 1} review rows.`);

// Load products
const csvProductsContent = fs.readFileSync(path.join(__dirname, "../src/csvProducts.ts"), "utf8");
const productsMatch = csvProductsContent.match(/export const CSV_PRODUCTS = (\[[\s\S]*?\]);/);
let products = [];
if (productsMatch) {
  products = eval(productsMatch[1]);
}

console.log(`Loaded ${products.length} products from csvProducts.ts.`);

// Build clean reviews list
const clientReviews = [];
for (let i = 1; i < parsedRows.length; i++) {
  const row = parsedRows[i];
  if (row.length < 6) continue;

  const rawProdId = row[0].trim();
  const rawProdName = row[1].trim();
  const author = row[2].trim();
  const rating = Number(row[3]) || 5;
  const dateStr = row[4].trim();
  const commentText = row[5].trim();

  // Smart match product
  let matchedProd = products.find(p => p.id === rawProdId);
  if (!matchedProd) {
    matchedProd = products.find(p => p.name.toLowerCase().trim() === rawProdName.toLowerCase().trim());
  }
  if (!matchedProd) {
    matchedProd = products.find(p => p.name.toLowerCase().includes(rawProdName.toLowerCase().trim()) || rawProdName.toLowerCase().includes(p.name.toLowerCase().trim()));
  }

  // Extract review title from first sentence of commentText
  const firstSentence = commentText.split(". ")[0].replace(/[".]/g, "").trim();
  const title = firstSentence.length > 60 ? firstSentence.slice(0, 57) + "..." : firstSentence;

  clientReviews.push({
    id: `client-rev-${rawProdId}-${i}`,
    productId: matchedProd ? matchedProd.id : rawProdId,
    productName: matchedProd ? matchedProd.name : rawProdName,
    author: author,
    name: author,
    rating: rating,
    title: title,
    comment: commentText,
    date: dateStr,
    status: "approved",
    verified: true,
    created_at: new Date(dateStr).toISOString()
  });
}

console.log(`Generated ${clientReviews.length} client review objects.`);

// Write src/data/clientReviews.ts
const tsContent = `// Client-Provided Product Reviews for TwoBudz Formulas
import { ReviewItem } from "../types";

export const CLIENT_REVIEWS: ReviewItem[] = ${JSON.stringify(clientReviews, null, 2)};
`;

fs.writeFileSync(path.join(__dirname, "../src/clientReviews.ts"), tsContent, "utf8");
console.log("Successfully wrote src/clientReviews.ts!");
