const fs = require("fs");
const path = require("path");

const rawCsvText = `Product Name,Reviewer Name,Rating Score (1-5),Review Headline,Detailed Review Comment,Date,Product ID,Review ID
Willie's Remedy THC Infused Seltzer Strawberry Watermelon,Xan Pruitt,5,"Decent, but a bit mixed for me","Decent, but a bit mixed for me. It's a refreshing, easy-drinking option for something low-key. Nice alternative to a cocktail on a night out. One small thing - wish the flavor was a little stronger. At around $7.99, I think it's fairly priced for a drink of this quality. Fine for the price, wouldn't go out of my way for it though.","March 21, 2026",prod-1783884305648,seed-rev-prod-1783884305648-1
Willie's Remedy THC Infused Seltzer Strawberry Watermelon,Oakley Dunham,5,"Decent, but a bit mixed for me","Decent, but a bit mixed for me. It's a refreshing, easy-drinking option for something low-key. Good option when i want to skip alcohol but still unwind. The Flower Mound TwoBudz team recommended this one and it didn't disappoint. One small thing - packaging could be better sealed. At around $7.99, I think it's fairly priced for a drink of this quality. Might try a different flavor or size next time.","July 5, 2026",prod-1783884305648,seed-rev-prod-1783884305648-2
Willie's Remedy THC Infused Seltzer Strawberry Watermelon,Amara Jensen,4,"Solid pick overall, just a couple small notes","Solid pick overall, just a couple small notes. It's a refreshing, easy-drinking option for something low-key. Nice alternative to a cocktail on a night out. The Flower Mound TwoBudz team recommended this one and it didn't disappoint. At around $7.99, I think it's fairly priced for a drink of this quality. Worth it even with the small downside.","May 20, 2026",prod-1783884305648,seed-rev-prod-1783884305648-3
Willie's Remedy THC Infused Seltzer Strawberry Watermelon,Mika B.,4,"Decent, but a bit mixed for me","Decent, but a bit mixed for me. It's a refreshing, easy-drinking option for something low-key. Good option when i want to skip alcohol but still unwind. One small thing - flavor was a bit more muted than I hoped. At around $7.99, I think it's fairly priced for a drink of this quality. Not bad, but I'll probably look at other options too.","June 24, 2026",prod-1783884305648,seed-rev-prod-1783884305648-4
Willie's Remedy THC Infused Seltzer Strawberry Watermelon,Brennan L.,5,Really happy with this one,"Really happy with this one. It's a refreshing, easy-drinking option for something low-key. Good option when i want to skip alcohol but still unwind. At around $7.99, I think it's fairly priced for a drink of this quality. This earned a permanent spot on my shopping list.","June 22, 2026",prod-1783884305648,seed-rev-prod-1783884305648-5
Willie's Remedy THC Infused Seltzer Black Cherry Lime,Brennan,5,"It's fine - does the job, nothing exceptional","It's fine - does the job, nothing exceptional. Easy to dose out with the dropper, and it mixes in cleanly if you're adding it to a drink or taking it straight. Part of my morning wellness routine now. One small thing - would like a slightly bigger size option. At around $7.99, I think it's fairly priced for a oil/tincture of this quality. Not bad, but I'll probably look at other options too.","February 27, 2026",prod-1783883747826,seed-rev-prod-1783883747826-1
Willie's Remedy THC Infused Seltzer Black Cherry Lime,Yael Underwood,4,"Really good, though not quite perfect","Really good, though not quite perfect. Easy to dose out with the dropper, and it mixes in cleanly if you're adding it to a drink or taking it straight. Easy to work into a daily cbd routine. At around $7.99, I think it's fairly priced for a oil/tincture of this quality. Would still buy again.","June 15, 2026",prod-1783883747826,seed-rev-prod-1783883747826-2
Willie's Remedy THC Infused Seltzer Black Cherry Lime,Avery R.,5,Glad I tried it - a few minor things keep it from a perfect score,"Glad I tried it - a few minor things keep it from a perfect score. Easy to dose out with the dropper, and it mixes in cleanly if you're adding it to a drink or taking it straight. Part of my morning wellness routine now. At around $7.99, I think it's fairly priced for a oil/tincture of this quality. Minor gripes aside, I'd repurchase.","February 8, 2026",prod-1783883747826,seed-rev-prod-1783883747826-3
Willie's Remedy THC Infused Seltzer Black Cherry Lime,Lior Young,5,"Really good, though not quite perfect","Really good, though not quite perfect. Easy to dose out with the dropper, and it mixes in cleanly if you're adding it to a drink or taking it straight. Part of my morning wellness routine now. At around $7.99, I think it's fairly priced for a oil/tincture of this quality. Worth it even with the small downside.","June 25, 2026",prod-1783883747826,seed-rev-prod-1783883747826-4
Willie's Remedy THC Infused Seltzer Black Cherry Lime,Micah,5,Honestly one of my favorite finds at this store,"Honestly one of my favorite finds at this store. Easy to dose out with the dropper, and it mixes in cleanly if you're adding it to a drink or taking it straight. Good for daily stress management. At around $7.99, I think it's fairly priced for a oil/tincture of this quality. Great value for the price.","July 24, 2026",prod-1783883747826,seed-rev-prod-1783883747826-5
Willie's THC Social Tonic 5mg 750ml Spirit,Elliot E.,4,Didn't expect to like this as much as I do,"Didn't expect to like this as much as I do. Easy to dose out with the dropper, and it mixes in cleanly if you're adding it to a drink or taking it straight. Good for daily stress management. At around $54.99, I think it's fairly priced for a oil/tincture of this quality. Would buy again.","January 28, 2026",prod-1783882836256,seed-rev-prod-1783882836256-1
Willie's THC Social Tonic 5mg 750ml Spirit,Devon Turner,4,Really happy with this one,"Really happy with this one. Easy to dose out with the dropper, and it mixes in cleanly if you're adding it to a drink or taking it straight. Helps take the edge off before a busy day. At around $54.99, I think it's fairly priced for a oil/tincture of this quality. Will be back for more.","March 25, 2026",prod-1783882836256,seed-rev-prod-1783882836256-2
Willie's THC Social Tonic 5mg 750ml Spirit,Zion S.,5,Better than I expected,"Better than I expected. Easy to dose out with the dropper, and it mixes in cleanly if you're adding it to a drink or taking it straight. Helps take the edge off before a busy day. At around $54.99, I think it's fairly priced for a oil/tincture of this quality. Will be back for more.","January 14, 2026",prod-1783882836256,seed-rev-prod-1783882836256-3
Willie's THC Social Tonic 5mg 750ml Spirit,Dario,5,Really happy with this one,"Really happy with this one. Easy to dose out with the dropper, and it mixes in cleanly if you're adding it to a drink or taking it straight. Easy to work into a daily cbd routine. At around $54.99, I think it's fairly priced for a oil/tincture of this quality. This earned a permanent spot on my shopping list.","July 26, 2026",prod-1783882836256,seed-rev-prod-1783882836256-4
Willie's THC Social Tonic 5mg 750ml Spirit,Mika P.,5,Impressed from the first time I tried it,"Impressed from the first time I tried it. Easy to dose out with the dropper, and it mixes in cleanly if you're adding it to a drink or taking it straight. Helps take the edge off before a busy day. At around $54.99, I think it's fairly priced for a oil/tincture of this quality. Worth every penny.","June 8, 2026",prod-1783882836256,seed-rev-prod-1783882836256-5
Willie's THC Social Tonic 10mg 750ml Spirit,Sam W.,5,Honestly one of my favorite finds at this store,"Honestly one of my favorite finds at this store. Applies smoothly and absorbs quickly without leaving a greasy residue behind. Helps with joint stiffness in the morning. At around $69.99, I think it's fairly priced for a topical of this quality. Will be back for more.","January 15, 2026",prod-1783882226404,seed-rev-prod-1783882226404-1
Willie's THC Social Tonic 10mg 750ml Spirit,Ira Monroe,5,Couldn't be happier with this purchase,"Couldn't be happier with this purchase. Applies smoothly and absorbs quickly without leaving a greasy residue behind. Helps with joint stiffness in the morning. At around $69.99, I think it's fairly priced for a topical of this quality. Great value for the price.","March 21, 2026",prod-1783882226404,seed-rev-prod-1783882226404-2
Willie's THC Social Tonic 10mg 750ml Spirit,Emery Vance,5,"Solid pick overall, just a couple small notes","Solid pick overall, just a couple small notes. Applies smoothly and absorbs quickly without leaving a greasy residue behind. Part of my post-workout recovery routine. At around $69.99, I think it's fairly priced for a topical of this quality. Solid enough that I'll grab it again.","June 17, 2026",prod-1783882226404,seed-rev-prod-1783882226404-3
Willie's THC Social Tonic 10mg 750ml Spirit,Esme Dunham,5,Really happy with this one,"Really happy with this one. Applies smoothly and absorbs quickly without leaving a greasy residue behind. Good for sore muscles after a workout. At around $69.99, I think it's fairly priced for a topical of this quality. Worth every penny.","March 16, 2026",prod-1783882226404,seed-rev-prod-1783882226404-4
Willie's THC Social Tonic 10mg 750ml Spirit,Harper Anderson,5,Honestly one of my favorite finds at this store,"Honestly one of my favorite finds at this store. Applies smoothly and absorbs quickly without leaving a greasy residue behind. Good for tension after a long day on my feet. At around $69.99, I think it's fairly priced for a topical of this quality. Would buy again.","July 27, 2026",prod-1783882226404,seed-rev-prod-1783882226404-5
Wyld CBD Sparkling Water - Lemon 50mg,Adrian Monroe,5,Better than I expected,"Better than I expected. The Lemon flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. A solid alcohol-free option for get-togethers. At around $5.99, I think it's fairly priced for a drink of this quality. Worth every penny.","May 23, 2026",62,seed-rev-62-1
Wyld CBD Sparkling Water - Lemon 50mg,Jules X.,5,Didn't expect to like this as much as I do,"Didn't expect to like this as much as I do. The Lemon flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Nice alternative to a cocktail on a night out. At around $5.99, I think it's fairly priced for a drink of this quality. Already recommended it to a friend.","January 28, 2026",62,seed-rev-62-2
Wyld CBD Sparkling Water - Lemon 50mg,Sawyer U.,5,Impressed from the first time I tried it,"Impressed from the first time I tried it. The Lemon flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Nice alternative to a cocktail on a night out. The Flower Mound TwoBudz team recommended this one and it didn't disappoint. At around $5.99, I think it's fairly priced for a drink of this quality. This earned a permanent spot on my shopping list.","January 19, 2026",62,seed-rev-62-3
Wyld CBD Sparkling Water - Lemon 50mg,Vance A.,4,"Really good, though not quite perfect","Really good, though not quite perfect. The Lemon flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Good option when i want to skip alcohol but still unwind. The Flower Mound TwoBudz team recommended this one and it didn't disappoint. At around $5.99, I think it's fairly priced for a drink of this quality. Would still buy again.","April 23, 2026",62,seed-rev-62-4
Wyld CBD Sparkling Water - Lemon 50mg,Brennan Kessler,5,Couldn't be happier with this purchase,"Couldn't be happier with this purchase. The Lemon flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Good option when i want to skip alcohol but still unwind. At around $5.99, I think it's fairly priced for a drink of this quality. Will be back for more.","June 16, 2026",62,seed-rev-62-5
Wyld CBD Sparkling Water - Raspberry 50mg,Winter Griffin,4,Glad I tried it - a few minor things keep it from a perfect score,"Glad I tried it - a few minor things keep it from a perfect score. The Raspberry flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Nice alternative to a cocktail on a night out. At around $5.99, I think it's fairly priced for a drink of this quality. Worth it even with the small downside.","February 8, 2026",61,seed-rev-61-1
Wyld CBD Sparkling Water - Raspberry 50mg,Lior P.,3,"It's fine - does the job, nothing exceptional","It's fine - does the job, nothing exceptional. The Raspberry flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Good for a relaxed evening without the hangover. One small thing - wish the flavor was a little stronger. At around $5.99, I think it's fairly priced for a drink of this quality. Might try a different flavor or size next time.","April 21, 2026",61,seed-rev-61-2
Wyld CBD Sparkling Water - Raspberry 50mg,Rowan Turner,3,"Middle-of-the-road experience, some pros and cons","Middle-of-the-road experience, some pros and cons. The Raspberry flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. An easy swap for beer at a barbecue. One small thing - the size felt a little small for the price. At around $5.99, I think it's fairly priced for a drink of this quality. Fine for the price, wouldn't go out of my way for it though.","May 1, 2026",61,seed-rev-61-3
Wyld CBD Sparkling Water - Raspberry 50mg,Winter Kessler,3,"It's fine - does the job, nothing exceptional","It's fine - does the job, nothing exceptional. The Raspberry flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Good for a relaxed evening without the hangover. One small thing - wish the flavor was a little stronger. At around $5.99, I think it's fairly priced for a drink of this quality. Not bad, but I'll probably look at other options too.","January 12, 2026",61,seed-rev-61-4
Wyld CBD Sparkling Water - Raspberry 50mg,Noel Turner,5,This has become a regular pickup for me,"This has become a regular pickup for me. The Raspberry flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Nice alternative to a cocktail on a night out. At around $5.99, I think it's fairly priced for a drink of this quality. Would buy again.","April 18, 2026",61,seed-rev-61-5
Enjoy Sleep 3300mg CBD + CBN Mixed Fruit Gummies,Jesse B.,4,"Really good, though not quite perfect","Really good, though not quite perfect. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for a mellow weekend afternoon. Found it during a visit to the Flower Mound shop and it's been in my rotation since. At around $5.99, I think it's fairly priced for a gummy of this quality. Worth it even with the small downside.","March 18, 2026",190,seed-rev-190-1
Enjoy Sleep 3300mg CBD + CBN Mixed Fruit Gummies,Shawn Jensen,5,This is now a staple in my rotation,"This is now a staple in my rotation. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Great for winding down after work. At around $5.99, I think it's fairly priced for a gummy of this quality. Already recommended it to a friend.","March 27, 2026",190,seed-rev-190-2
Enjoy Sleep 3300mg CBD + CBN Mixed Fruit Gummies,Ursula Sutton,5,Impressed from the first time I tried it,"Impressed from the first time I tried it. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for a mellow weekend afternoon. At around $5.99, I think it's fairly priced for a gummy of this quality. Would buy again.","June 20, 2026",190,seed-rev-190-3
Enjoy Sleep 3300mg CBD + CBN Mixed Fruit Gummies,Cameron,5,Better than I expected,"Better than I expected. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Works well as a low-key nighttime routine. At around $5.99, I think it's fairly priced for a gummy of this quality. Worth every penny.","April 12, 2026",190,seed-rev-190-4
Enjoy Sleep 3300mg CBD + CBN Mixed Fruit Gummies,Kit Underwood,3,"Decent, but a bit mixed for me","Decent, but a bit mixed for me. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for a mellow weekend afternoon. One small thing - the size felt a little small for the price. At around $5.99, I think it's fairly priced for a gummy of this quality. Worth trying once to see if it's for you.","February 16, 2026",190,seed-rev-190-5
Wyld Marionberry Indica THC Gummies - 10mg,Priya V.,4,"Really good, though not quite perfect","Really good, though not quite perfect. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for a mellow weekend afternoon. At around $64.99, I think it's fairly priced for a gummy of this quality. Solid enough that I'll grab it again.","June 18, 2026",184,seed-rev-184-1
Wyld Marionberry Indica THC Gummies - 10mg,Uma E.,5,This quickly became my go-to,"This quickly became my go-to. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. A nice option for easing into sleep. At around $64.99, I think it's fairly priced for a gummy of this quality. Would buy again.","June 4, 2026",184,seed-rev-184-2
Wyld Marionberry Indica THC Gummies - 10mg,Blake,3,"It's fine - does the job, nothing exceptional","It's fine - does the job, nothing exceptional. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for a mellow weekend afternoon. One small thing - packaging could be better sealed. At around $64.99, I think it's fairly priced for a gummy of this quality. Fine for the price, wouldn't go out of my way for it though.","April 21, 2026",184,seed-rev-184-3
Wyld Marionberry Indica THC Gummies - 10mg,Alex Dunham,5,Really happy with this one,"Really happy with this one. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. A nice option for easing into sleep. At around $64.99, I think it's fairly priced for a gummy of this quality. Already recommended it to a friend.","July 24, 2026",184,seed-rev-184-4
Wyld Marionberry Indica THC Gummies - 10mg,Parker Bishop,5,Really happy with this one,"Really happy with this one. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for a mellow weekend afternoon. At around $64.99, I think it's fairly priced for a gummy of this quality. Great value for the price.","January 24, 2026",184,seed-rev-184-5
Nowadays 10 mg THC Shot,Amara T.,3,"Decent, but a bit mixed for me","Decent, but a bit mixed for me. It's a refreshing, easy-drinking option for something low-key. Good option when i want to skip alcohol but still unwind. One small thing - packaging could be better sealed. At around $7.99, I think it's fairly priced for a drink of this quality. Not bad, but I'll probably look at other options too.","April 28, 2026",182,seed-rev-182-1
Nowadays 10 mg THC Shot,Gia,4,Good experience overall with one small nitpick,"Good experience overall with one small nitpick. It's a refreshing, easy-drinking option for something low-key. Good option when i want to skip alcohol but still unwind. At around $7.99, I think it's fairly priced for a drink of this quality. Worth it even with the small downside.","March 11, 2026",182,seed-rev-182-2
Nowadays 10 mg THC Shot,Ira S.,5,Didn't expect to like this as much as I do,"Didn't expect to like this as much as I do. It's a refreshing, easy-drinking option for something low-key. Good option when i want to skip alcohol but still unwind. At around $7.99, I think it's fairly priced for a drink of this quality. Would buy again.","January 8, 2026",182,seed-rev-182-3
Nowadays 10 mg THC Shot,Esme F.,5,Really happy with this one,"Really happy with this one. It's a refreshing, easy-drinking option for something low-key. Good for a relaxed evening without the hangover. At around $7.99, I think it's fairly priced for a drink of this quality. This earned a permanent spot on my shopping list.","March 13, 2026",182,seed-rev-182-4
Nowadays 10 mg THC Shot,Uma D.,5,This is now a staple in my rotation,"This is now a staple in my rotation. It's a refreshing, easy-drinking option for something low-key. Good option when i want to skip alcohol but still unwind. Grabbed this at the TwoBudz Flower Mound location on a recommendation from a staff member. At around $7.99, I think it's fairly priced for a drink of this quality. Would buy again.","July 18, 2026",182,seed-rev-182-5
Proleve CBD Roll-On Cooling 2000mg,Yusuf I.,3,"It's fine - does the job, nothing exceptional","It's fine - does the job, nothing exceptional. Applies smoothly and absorbs quickly without leaving a greasy residue behind. Part of my post-workout recovery routine. Picked it up at the Flower Mound store and the staff pointed me toward it - glad they did. One small thing - would like a slightly bigger size option. At around $39.99, I think it's fairly priced for a topical of this quality. Worth trying once to see if it's for you.","June 21, 2026",141,seed-rev-141-1
Proleve CBD Roll-On Cooling 2000mg,Esme Monroe,4,"Solid pick overall, just a couple small notes","Solid pick overall, just a couple small notes. Applies smoothly and absorbs quickly without leaving a greasy residue behind. Helps with joint stiffness in the morning. At around $39.99, I think it's fairly priced for a topical of this quality. Worth it even with the small downside.","February 19, 2026",141,seed-rev-141-2
Proleve CBD Roll-On Cooling 2000mg,Yael Ibarra,5,Impressed from the first time I tried it,"Impressed from the first time I tried it. Applies smoothly and absorbs quickly without leaving a greasy residue behind. Good for sore muscles after a workout. At around $39.99, I think it's fairly priced for a topical of this quality. This earned a permanent spot on my shopping list.","January 20, 2026",141,seed-rev-141-3
Proleve CBD Roll-On Cooling 2000mg,Ira,5,Really happy with this one,"Really happy with this one. Applies smoothly and absorbs quickly without leaving a greasy residue behind. Helps with joint stiffness in the morning. At around $39.99, I think it's fairly priced for a topical of this quality. This earned a permanent spot on my shopping list.","July 15, 2026",141,seed-rev-141-4
Proleve CBD Roll-On Cooling 2000mg,Kai W.,5,This is now a staple in my rotation,"This is now a staple in my rotation. Applies smoothly and absorbs quickly without leaving a greasy residue behind. Helps with joint stiffness in the morning. At around $39.99, I think it's fairly priced for a topical of this quality. Great value for the price.","January 13, 2026",141,seed-rev-141-5
Enjoy Balance THC + CBD,Priya S.,5,Better than I expected,"Better than I expected. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Helps me relax without feeling knocked out. At around $59.99, I think it's fairly priced for a gummy of this quality. Great value for the price.","May 11, 2026",192,seed-rev-192-1
Enjoy Balance THC + CBD,Yael A.,5,Didn't expect to like this as much as I do,"Didn't expect to like this as much as I do. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. A nice option for easing into sleep. At around $59.99, I think it's fairly priced for a gummy of this quality. Great value for the price.","July 21, 2026",192,seed-rev-192-2
Enjoy Balance THC + CBD,Kai Lambert,5,This quickly became my go-to,"This quickly became my go-to. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for a mellow weekend afternoon. At around $59.99, I think it's fairly priced for a gummy of this quality. This earned a permanent spot on my shopping list.","June 26, 2026",192,seed-rev-192-3
Enjoy Balance THC + CBD,Kit P.,5,Better than I expected,"Better than I expected. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Helps me relax without feeling knocked out. At around $59.99, I think it's fairly priced for a gummy of this quality. Can't recommend it enough.","March 1, 2026",192,seed-rev-192-4
Enjoy Balance THC + CBD,Jules D.,4,"Solid pick overall, just a couple small notes","Solid pick overall, just a couple small notes. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Helps me relax without feeling knocked out. At around $59.99, I think it's fairly priced for a gummy of this quality. Worth it even with the small downside.","March 5, 2026",192,seed-rev-192-5
Barney's Botanicals 12mg Delta 9 Gummies 10ct,Peyton Vance,5,This quickly became my go-to,"This quickly became my go-to. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Works well as a low-key nighttime routine. At around $19.99, I think it's fairly priced for a gummy of this quality. Would buy again.","March 11, 2026",96,seed-rev-96-1
Barney's Botanicals 12mg Delta 9 Gummies 10ct,Charlie J.,3,"Decent, but a bit mixed for me","Decent, but a bit mixed for me. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for taking the edge off in the evening. One small thing - packaging could be better sealed. At around $19.99, I think it's fairly priced for a gummy of this quality. Fine for the price, wouldn't go out of my way for it though.","February 23, 2026",96,seed-rev-96-2
Barney's Botanicals 12mg Delta 9 Gummies 10ct,Farid O.,5,Couldn't be happier with this purchase,"Couldn't be happier with this purchase. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Great for winding down after work. At around $19.99, I think it's fairly priced for a gummy of this quality. Will be back for more.","April 2, 2026",96,seed-rev-96-3
Barney's Botanicals 12mg Delta 9 Gummies 10ct,Amara J.,4,"Solid pick overall, just a couple small notes","Solid pick overall, just a couple small notes. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for a mellow weekend afternoon. Grabbed this at the TwoBudz Flower Mound location on a recommendation from a staff member. At around $19.99, I think it's fairly priced for a gummy of this quality. Worth it even with the small downside.","March 12, 2026",96,seed-rev-96-4
Barney's Botanicals 12mg Delta 9 Gummies 10ct,Dario,3,"Middle-of-the-road experience, some pros and cons","Middle-of-the-road experience, some pros and cons. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. A nice option for easing into sleep. One small thing - wish the flavor was a little stronger. At around $19.99, I think it's fairly priced for a gummy of this quality. Might try a different flavor or size next time.","June 28, 2026",96,seed-rev-96-5
Proleve CBD 2000 Warming Roll On,Owen Ortiz,5,Honestly one of my favorite finds at this store,"Honestly one of my favorite finds at this store. Applies smoothly and absorbs quickly without leaving a greasy residue behind. Good for sore muscles after a workout. At around $39.99, I think it's fairly priced for a topical of this quality. Great value for the price.","January 21, 2026",140,seed-rev-140-1
Proleve CBD 2000 Warming Roll On,Vance Jensen,5,Better than I expected,"Better than I expected. Applies smoothly and absorbs quickly without leaving a greasy residue behind. Good for tension after a long day on my feet. At around $39.99, I think it's fairly priced for a topical of this quality. This earned a permanent spot on my shopping list.","June 14, 2026",140,seed-rev-140-2
Proleve CBD 2000 Warming Roll On,Peyton Ellison,5,This quickly became my go-to,"This quickly became my go-to. Applies smoothly and absorbs quickly without leaving a greasy residue behind. Good for tension after a long day on my feet. At around $39.99, I think it's fairly priced for a topical of this quality. Great value for the price.","May 8, 2026",140,seed-rev-140-3
Proleve CBD 2000 Warming Roll On,Zion,5,Really happy with this one,"Really happy with this one. Applies smoothly and absorbs quickly without leaving a greasy residue behind. Good for tension after a long day on my feet. Found it during a visit to the Flower Mound shop and it's been in my rotation since. At around $39.99, I think it's fairly priced for a topical of this quality. Can't recommend it enough.","July 15, 2026",140,seed-rev-140-4
Proleve CBD 2000 Warming Roll On,Avery Quinn,5,Really happy with this one,"Really happy with this one. Applies smoothly and absorbs quickly without leaving a greasy residue behind. Part of my post-workout recovery routine. At around $39.99, I think it's fairly priced for a topical of this quality. Already recommended it to a friend.","July 11, 2026",140,seed-rev-140-5
Road Trip Desert Stardust Mushroom Chocolate Bar - Strawberry Crunch,Wren Ferrell,4,Glad I tried it - a few minor things keep it from a perfect score,"Glad I tried it - a few minor things keep it from a perfect score. The Strawberry Crunch flavor comes through clearly and it's a fun, discreet snack to have on hand. A fun discreet snack for road trips. Found it during a visit to the Flower Mound shop and it's been in my rotation since. At around $24.99, I think it's fairly priced for a edible of this quality. Would still buy again.","March 4, 2026",170,seed-rev-170-1
Road Trip Desert Stardust Mushroom Chocolate Bar - Strawberry Crunch,Taylor H.,5,This has become a regular pickup for me,"This has become a regular pickup for me. The Strawberry Crunch flavor comes through clearly and it's a fun, discreet snack to have on hand. Works well as an easy on-the-go option. At around $24.99, I think it's fairly priced for a edible of this quality. Will be back for more.","July 4, 2026",170,seed-rev-170-2
Road Trip Desert Stardust Mushroom Chocolate Bar - Strawberry Crunch,Jules X.,3,"It's fine - does the job, nothing exceptional","It's fine - does the job, nothing exceptional. The Strawberry Crunch flavor comes through clearly and it's a fun, discreet snack to have on hand. Good for a low-key evening treat. One small thing - the size felt a little small for the price. At around $24.99, I think it's fairly priced for a edible of this quality. Might try a different flavor or size next time.","March 11, 2026",170,seed-rev-170-3
Road Trip Desert Stardust Mushroom Chocolate Bar - Strawberry Crunch,Wren V.,5,This has become a regular pickup for me,"This has become a regular pickup for me. The Strawberry Crunch flavor comes through clearly and it's a fun, discreet snack to have on hand. A fun discreet snack for road trips. At around $24.99, I think it's fairly priced for a edible of this quality. Great value for the price.","February 23, 2026",170,seed-rev-170-4
Road Trip Desert Stardust Mushroom Chocolate Bar - Strawberry Crunch,Talia L.,5,Honestly one of my favorite finds at this store,"Honestly one of my favorite finds at this store. The Strawberry Crunch flavor comes through clearly and it's a fun, discreet snack to have on hand. Works well as an easy on-the-go option. At around $24.99, I think it's fairly priced for a edible of this quality. Can't recommend it enough.","June 6, 2026",170,seed-rev-170-5
Drink Delta D9 Water - Maui Wowie Passion Fruit 20mg,Jordan F.,4,"Really good, though not quite perfect","Really good, though not quite perfect. The Maui Wowie Passion Fruit flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. An easy swap for beer at a barbecue. At around $6.99, I think it's fairly priced for a drink of this quality. Minor gripes aside, I'd repurchase.","May 22, 2026",95,seed-rev-95-1
Drink Delta D9 Water - Maui Wowie Passion Fruit 20mg,Brennan Brooks,3,"Decent, but a bit mixed for me","Decent, but a bit mixed for me. The Maui Wowie Passion Fruit flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. A solid alcohol-free option for get-togethers. One small thing - wish the flavor was a little stronger. At around $6.99, I think it's fairly priced for a drink of this quality. Fine for the price, wouldn't go out of my way for it though.","February 14, 2026",95,seed-rev-95-2
Drink Delta D9 Water - Maui Wowie Passion Fruit 20mg,Jonah Monroe,5,This has become a regular pickup for me,"This has become a regular pickup for me. The Maui Wowie Passion Fruit flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Works well as a light social drink. Picked it up at the Flower Mound store and the staff pointed me toward it - glad they did. At around $6.99, I think it's fairly priced for a drink of this quality. Will be back for more.","January 3, 2026",95,seed-rev-95-3
Drink Delta D9 Water - Maui Wowie Passion Fruit 20mg,Micah Monroe,5,Better than I expected,"Better than I expected. The Maui Wowie Passion Fruit flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. An easy swap for beer at a barbecue. Picked it up at the Flower Mound store and the staff pointed me toward it - glad they did. At around $6.99, I think it's fairly priced for a drink of this quality. Already recommended it to a friend.","January 6, 2026",95,seed-rev-95-4
Drink Delta D9 Water - Maui Wowie Passion Fruit 20mg,Skylar Sutton,4,Glad I tried it - a few minor things keep it from a perfect score,"Glad I tried it - a few minor things keep it from a perfect score. The Maui Wowie Passion Fruit flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. A solid alcohol-free option for get-togethers. At around $6.99, I think it's fairly priced for a drink of this quality. Minor gripes aside, I'd repurchase.","July 24, 2026",95,seed-rev-95-5
Drink Delta D9 Water - Wedding Cake Blood Orange 20mg,Yael L.,5,This is now a staple in my rotation,"This is now a staple in my rotation. The Wedding Cake Blood Orange flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Good for a relaxed evening without the hangover. At around $6.99, I think it's fairly priced for a drink of this quality. Worth every penny.","May 1, 2026",94,seed-rev-94-1
Drink Delta D9 Water - Wedding Cake Blood Orange 20mg,Phoenix Q.,5,This is now a staple in my rotation,"This is now a staple in my rotation. The Wedding Cake Blood Orange flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Nice alternative to a cocktail on a night out. At around $6.99, I think it's fairly priced for a drink of this quality. Already recommended it to a friend.","July 15, 2026",94,seed-rev-94-2
Drink Delta D9 Water - Wedding Cake Blood Orange 20mg,Nadia Ferrell,4,"Solid pick overall, just a couple small notes","Solid pick overall, just a couple small notes. The Wedding Cake Blood Orange flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. A solid alcohol-free option for get-togethers. At around $6.99, I think it's fairly priced for a drink of this quality. Worth it even with the small downside.","January 8, 2026",94,seed-rev-94-3
Drink Delta D9 Water - Wedding Cake Blood Orange 20mg,Reese B.,5,Impressed from the first time I tried it,"Impressed from the first time I tried it. The Wedding Cake Blood Orange flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Works well as a light social drink. At around $6.99, I think it's fairly priced for a drink of this quality. Already recommended it to a friend.","January 5, 2026",94,seed-rev-94-4
Drink Delta D9 Water - Wedding Cake Blood Orange 20mg,Drew,5,This quickly became my go-to,"This quickly became my go-to. The Wedding Cake Blood Orange flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. An easy swap for beer at a barbecue. At around $6.99, I think it's fairly priced for a drink of this quality. Can't recommend it enough.","April 8, 2026",94,seed-rev-94-5
Enjoy Live Rosin Chill Delta 9 Gummies 600mg,Kendall Z.,5,Really happy with this one,"Really happy with this one. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for a mellow weekend afternoon. Found it during a visit to the Flower Mound shop and it's been in my rotation since. At around $74.99, I think it's fairly priced for a gummy of this quality. Worth every penny.","April 10, 2026",126,seed-rev-126-1
Enjoy Live Rosin Chill Delta 9 Gummies 600mg,Jonah F.,5,This has become a regular pickup for me,"This has become a regular pickup for me. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Helps me relax without feeling knocked out. At around $74.99, I think it's fairly priced for a gummy of this quality. Will be back for more.","January 15, 2026",126,seed-rev-126-2
Enjoy Live Rosin Chill Delta 9 Gummies 600mg,Sawyer Kessler,5,Impressed from the first time I tried it,"Impressed from the first time I tried it. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Helps me relax without feeling knocked out. At around $74.99, I think it's fairly priced for a gummy of this quality. Can't recommend it enough.","March 19, 2026",126,seed-rev-126-3
Enjoy Live Rosin Chill Delta 9 Gummies 600mg,Zion Diaz,4,Good experience overall with one small nitpick,"Good experience overall with one small nitpick. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for taking the edge off in the evening. At around $74.99, I think it's fairly priced for a gummy of this quality. Minor gripes aside, I'd repurchase.","January 21, 2026",126,seed-rev-126-4
Enjoy Live Rosin Chill Delta 9 Gummies 600mg,Zion S.,5,Exactly what I was looking for,"Exactly what I was looking for. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Great for winding down after work. At around $74.99, I think it's fairly priced for a gummy of this quality. Can't recommend it enough.","July 27, 2026",126,seed-rev-126-5
Enjoy Live Rosin Delta 9 + CBD Gummies Balance 25ct,Emerson,5,Really happy with this one,"Really happy with this one. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Helps me relax without feeling knocked out. At around $54.99, I think it's fairly priced for a gummy of this quality. Will be back for more.","April 5, 2026",120,seed-rev-120-1
Enjoy Live Rosin Delta 9 + CBD Gummies Balance 25ct,Wren D.,4,Good experience overall with one small nitpick,"Good experience overall with one small nitpick. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Great for winding down after work. At around $54.99, I think it's fairly priced for a gummy of this quality. Worth it even with the small downside.","February 18, 2026",120,seed-rev-120-2
Enjoy Live Rosin Delta 9 + CBD Gummies Balance 25ct,Riley Hayes,5,Honestly one of my favorite finds at this store,"Honestly one of my favorite finds at this store. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Helps me relax without feeling knocked out. At around $54.99, I think it's fairly priced for a gummy of this quality. Already recommended it to a friend.","February 2, 2026",120,seed-rev-120-3
Enjoy Live Rosin Delta 9 + CBD Gummies Balance 25ct,Tatum Kessler,5,Honestly one of my favorite finds at this store,"Honestly one of my favorite finds at this store. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. A nice option for easing into sleep. At around $54.99, I think it's fairly priced for a gummy of this quality. Already recommended it to a friend.","June 26, 2026",120,seed-rev-120-4
Enjoy Live Rosin Delta 9 + CBD Gummies Balance 25ct,Skylar Griffin,4,Good experience overall with one small nitpick,"Good experience overall with one small nitpick. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for taking the edge off in the evening. At around $54.99, I think it's fairly priced for a gummy of this quality. Worth it even with the small downside.","January 18, 2026",120,seed-rev-120-5
Wyld CBD Sparkling Water - Grapefruit 20mg CBD + 10mg CBG,Vance,4,"Really good, though not quite perfect","Really good, though not quite perfect. The Grapefruit  CBD +  CBG flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Works well as a light social drink. At around $5.99, I think it's fairly priced for a drink of this quality. Would still buy again.","February 5, 2026",59,seed-rev-59-1
Wyld CBD Sparkling Water - Grapefruit 20mg CBD + 10mg CBG,Dario N.,5,This has become a regular pickup for me,"This has become a regular pickup for me. The Grapefruit  CBD +  CBG flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Good option when i want to skip alcohol but still unwind. At around $5.99, I think it's fairly priced for a drink of this quality. Already recommended it to a friend.","July 1, 2026",59,seed-rev-59-2
Wyld CBD Sparkling Water - Grapefruit 20mg CBD + 10mg CBG,Emery Quinn,5,Really happy with this one,"Really happy with this one. The Grapefruit  CBD +  CBG flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Nice alternative to a cocktail on a night out. At around $5.99, I think it's fairly priced for a drink of this quality. Worth every penny.","April 28, 2026",59,seed-rev-59-3
Wyld CBD Sparkling Water - Grapefruit 20mg CBD + 10mg CBG,Jesse F.,3,"It's fine - does the job, nothing exceptional","It's fine - does the job, nothing exceptional. The Grapefruit  CBD +  CBG flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. An easy swap for beer at a barbecue. One small thing - the size felt a little small for the price. At around $5.99, I think it's fairly priced for a drink of this quality. Fine for the price, wouldn't go out of my way for it though.","February 9, 2026",59,seed-rev-59-4
Wyld CBD Sparkling Water - Grapefruit 20mg CBD + 10mg CBG,Owen,5,Honestly one of my favorite finds at this store,"Honestly one of my favorite finds at this store. The Grapefruit  CBD +  CBG flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Good option when i want to skip alcohol but still unwind. At around $5.99, I think it's fairly priced for a drink of this quality. Great value for the price.","July 2, 2026",59,seed-rev-59-5
Enjoy Live Rosin Delta 9 Gummies 300mg - Bliss,Ines Y.,5,Honestly one of my favorite finds at this store,"Honestly one of my favorite finds at this store. The Bliss flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. A nice option for easing into sleep. At around $44.99, I think it's fairly priced for a gummy of this quality. Already recommended it to a friend.","May 27, 2026",27,seed-rev-27-1
Enjoy Live Rosin Delta 9 Gummies 300mg - Bliss,Vic,5,This is now a staple in my rotation,"This is now a staple in my rotation. The Bliss flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Helps me relax without feeling knocked out. At around $44.99, I think it's fairly priced for a gummy of this quality. Would buy again.","June 5, 2026",27,seed-rev-27-2
Enjoy Live Rosin Delta 9 Gummies 300mg - Bliss,Cameron Carter,4,Good experience overall with one small nitpick,"Good experience overall with one small nitpick. The Bliss flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Works well as a low-key nighttime routine. At around $44.99, I think it's fairly priced for a gummy of this quality. Solid enough that I'll grab it again.","February 25, 2026",27,seed-rev-27-3
Enjoy Live Rosin Delta 9 Gummies 300mg - Bliss,Kit Reyes,5,Impressed from the first time I tried it,"Impressed from the first time I tried it. The Bliss flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. A nice option for easing into sleep. At around $44.99, I think it's fairly priced for a gummy of this quality. This earned a permanent spot on my shopping list.","June 6, 2026",27,seed-rev-27-4
Enjoy Live Rosin Delta 9 Gummies 300mg - Bliss,Ines M.,5,Didn't expect to like this as much as I do,"Didn't expect to like this as much as I do. The Bliss flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Good for a mellow weekend afternoon. At around $44.99, I think it's fairly priced for a gummy of this quality. Would buy again.","February 13, 2026",27,seed-rev-27-5
Enjoy Live Rosin Delta 9 Gummies Euphoria 25ct,Emery H.,4,"Solid pick overall, just a couple small notes","Solid pick overall, just a couple small notes. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for taking the edge off in the evening. At around $44.99, I think it's fairly priced for a gummy of this quality. Minor gripes aside, I'd repurchase.","March 12, 2026",122,seed-rev-122-1
Enjoy Live Rosin Delta 9 Gummies Euphoria 25ct,Sawyer O.,5,Didn't expect to like this as much as I do,"Didn't expect to like this as much as I do. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Great for winding down after work. At around $44.99, I think it's fairly priced for a gummy of this quality. Already recommended it to a friend.","March 14, 2026",122,seed-rev-122-2
Enjoy Live Rosin Delta 9 Gummies Euphoria 25ct,Sage,5,Couldn't be happier with this purchase,"Couldn't be happier with this purchase. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for a mellow weekend afternoon. At around $44.99, I think it's fairly priced for a gummy of this quality. Can't recommend it enough.","June 20, 2026",122,seed-rev-122-3
Enjoy Live Rosin Delta 9 Gummies Euphoria 25ct,Jordan,3,"Decent, but a bit mixed for me","Decent, but a bit mixed for me. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Great for winding down after work. One small thing - packaging could be better sealed. At around $44.99, I think it's fairly priced for a gummy of this quality. Might try a different flavor or size next time.","July 12, 2026",122,seed-rev-122-4
Enjoy Live Rosin Delta 9 Gummies Euphoria 25ct,Cameron,5,This quickly became my go-to,"This quickly became my go-to. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Great for winding down after work. The Flower Mound TwoBudz team recommended this one and it didn't disappoint. At around $44.99, I think it's fairly priced for a gummy of this quality. Would buy again.","March 11, 2026",122,seed-rev-122-5
Hometown Hero Delta 9 Cocoa Crisp Cereal Bites,Vic V.,5,Exactly what I was looking for,"Exactly what I was looking for. It's a fun, discreet snack to have on hand and the flavor comes through clearly. Works well as an easy on-the-go option. At around $49.99, I think it's fairly priced for a edible of this quality. Worth every penny.","February 3, 2026",74,seed-rev-74-1
Hometown Hero Delta 9 Cocoa Crisp Cereal Bites,Gale J.,4,"Really good, though not quite perfect","Really good, though not quite perfect. It's a fun, discreet snack to have on hand and the flavor comes through clearly. Works well as an easy on-the-go option. At around $49.99, I think it's fairly priced for a edible of this quality. Worth it even with the small downside.","June 8, 2026",74,seed-rev-74-2
Hometown Hero Delta 9 Cocoa Crisp Cereal Bites,Alex Vance,4,Good experience overall with one small nitpick,"Good experience overall with one small nitpick. It's a fun, discreet snack to have on hand and the flavor comes through clearly. Works well as an easy on-the-go option. Found it during a visit to the Flower Mound shop and it's been in my rotation since. At around $49.99, I think it's fairly priced for a edible of this quality. Worth it even with the small downside.","May 15, 2026",74,seed-rev-74-3
Hometown Hero Delta 9 Cocoa Crisp Cereal Bites,Hollis,5,Impressed from the first time I tried it,"Impressed from the first time I tried it. It's a fun, discreet snack to have on hand and the flavor comes through clearly. Good for a low-key evening treat. At around $49.99, I think it's fairly priced for a edible of this quality. Can't recommend it enough.","June 24, 2026",74,seed-rev-74-4
Hometown Hero Delta 9 Cocoa Crisp Cereal Bites,Ellis R.,4,"Solid pick overall, just a couple small notes","Solid pick overall, just a couple small notes. It's a fun, discreet snack to have on hand and the flavor comes through clearly. A fun discreet snack for road trips. At around $49.99, I think it's fairly priced for a edible of this quality. Would still buy again.","April 18, 2026",74,seed-rev-74-5
Wyld CBD Sparkling Water - Blackberry 50mg,Morgan,5,Impressed from the first time I tried it,"Impressed from the first time I tried it. The Blackberry  CBD flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Works well as a light social drink. At around $5.99, I think it's fairly priced for a drink of this quality. Great value for the price.","March 23, 2026",63,seed-rev-63-1
Wyld CBD Sparkling Water - Blackberry 50mg,Jonah R.,5,Impressed from the first time I tried it,"Impressed from the first time I tried it. The Blackberry  CBD flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Good option when i want to skip alcohol but still unwind. At around $5.99, I think it's fairly priced for a drink of this quality. Would buy again.","April 7, 2026",63,seed-rev-63-2
Wyld CBD Sparkling Water - Blackberry 50mg,Jules K.,5,Honestly one of my favorite finds at this store,"Honestly one of my favorite finds at this store. The Blackberry  CBD flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Good for a relaxed evening without the hangover. At around $5.99, I think it's fairly priced for a drink of this quality. Will be back for more.","April 13, 2026",63,seed-rev-63-3
Wyld CBD Sparkling Water - Blackberry 50mg,Taylor P.,3,"Decent, but a bit mixed for me","Decent, but a bit mixed for me. The Blackberry  CBD flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. A solid alcohol-free option for get-togethers. One small thing - flavor was a bit more muted than I hoped. At around $5.99, I think it's fairly priced for a drink of this quality. Not bad, but I'll probably look at other options too.","January 16, 2026",63,seed-rev-63-4
Wyld CBD Sparkling Water - Blackberry 50mg,Dallas Dunham,5,Better than I expected,"Better than I expected. The Blackberry  CBD flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Works well as a light social drink. At around $5.99, I think it's fairly priced for a drink of this quality. This earned a permanent spot on my shopping list.","July 22, 2026",63,seed-rev-63-5
"Proleve - CBD Daily Gummies - 50 mg, 30 Count",Elliot Lambert,5,Didn't expect to like this as much as I do,"Didn't expect to like this as much as I do. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for taking the edge off in the evening. At around $64.99, I think it's fairly priced for a gummy of this quality. Can't recommend it enough.","July 11, 2026",158,seed-rev-158-1
"Proleve - CBD Daily Gummies - 50 mg, 30 Count",Lior Underwood,4,"Really good, though not quite perfect","Really good, though not quite perfect. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for taking the edge off in the evening. At around $64.99, I think it's fairly priced for a gummy of this quality. Minor gripes aside, I'd repurchase.","March 7, 2026",158,seed-rev-158-2
"Proleve - CBD Daily Gummies - 50 mg, 30 Count",Reagan T.,5,Better than I expected,"Better than I expected. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Great for winding down after work. At around $64.99, I think it's fairly priced for a gummy of this quality. Would buy again.","May 17, 2026",158,seed-rev-158-3
"Proleve - CBD Daily Gummies - 50 mg, 30 Count",Wes M.,5,Couldn't be happier with this purchase,"Couldn't be happier with this purchase. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Works well as a low-key nighttime routine. At around $64.99, I think it's fairly priced for a gummy of this quality. Will be back for more.","July 21, 2026",158,seed-rev-158-4
"Proleve - CBD Daily Gummies - 50 mg, 30 Count",Yusuf,5,Didn't expect to like this as much as I do,"Didn't expect to like this as much as I do. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. A nice option for easing into sleep. At around $64.99, I think it's fairly priced for a gummy of this quality. Will be back for more.","June 26, 2026",158,seed-rev-158-5
Wyld CBD Sparkling Water - Blood Orange 50mg,Shawn Carter,5,Honestly one of my favorite finds at this store,"Honestly one of my favorite finds at this store. The Blood Orange flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. An easy swap for beer at a barbecue. At around $5.99, I think it's fairly priced for a drink of this quality. Will be back for more.","April 24, 2026",60,seed-rev-60-1
Wyld CBD Sparkling Water - Blood Orange 50mg,Xan,3,"It's fine - does the job, nothing exceptional","It's fine - does the job, nothing exceptional. The Blood Orange flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Works well as a light social drink. The Flower Mound TwoBudz team recommended this one and it didn't disappoint. One small thing - took longer than I expected to feel anything. At around $5.99, I think it's fairly priced for a drink of this quality. Not bad, but I'll probably look at other options too.","January 6, 2026",60,seed-rev-60-2
Wyld CBD Sparkling Water - Blood Orange 50mg,Jae,4,Good experience overall with one small nitpick,"Good experience overall with one small nitpick. The Blood Orange flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Nice alternative to a cocktail on a night out. Grabbed this at the TwoBudz Flower Mound location on a recommendation from a staff member. At around $5.99, I think it's fairly priced for a drink of this quality. Minor gripes aside, I'd repurchase.","July 12, 2026",60,seed-rev-60-3
Wyld CBD Sparkling Water - Blood Orange 50mg,Lior Alcott,5,Better than I expected,"Better than I expected. The Blood Orange flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. Good option when i want to skip alcohol but still unwind. At around $5.99, I think it's fairly priced for a drink of this quality. This earned a permanent spot on my shopping list.","March 14, 2026",60,seed-rev-60-4
Wyld CBD Sparkling Water - Blood Orange 50mg,Brennan M.,3,"It's fine - does the job, nothing exceptional","It's fine - does the job, nothing exceptional. The Blood Orange flavor is refreshing without being overly sweet, and it's an easy, low-key drink to reach for. An easy swap for beer at a barbecue. One small thing - packaging could be better sealed. At around $5.99, I think it's fairly priced for a drink of this quality. Fine for the price, wouldn't go out of my way for it though.","January 12, 2026",60,seed-rev-60-5
Barney's Botanicals 30mg Delta 9 Gummies 30ct,Soren Reyes,5,Impressed from the first time I tried it,"Impressed from the first time I tried it. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Works well as a low-key nighttime routine. At around $74.99, I think it's fairly priced for a gummy of this quality. Worth every penny.","January 23, 2026",98,seed-rev-98-1
Barney's Botanicals 30mg Delta 9 Gummies 30ct,Soren Monroe,5,Really happy with this one,"Really happy with this one. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for taking the edge off in the evening. At around $74.99, I think it's fairly priced for a gummy of this quality. Great value for the price.","May 7, 2026",98,seed-rev-98-2
Barney's Botanicals 30mg Delta 9 Gummies 30ct,Skylar R.,4,Good experience overall with one small nitpick,"Good experience overall with one small nitpick. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for a mellow weekend afternoon. At around $74.99, I think it's fairly priced for a gummy of this quality. Solid enough that I'll grab it again.","March 26, 2026",98,seed-rev-98-3
Barney's Botanicals 30mg Delta 9 Gummies 30ct,Esme Young,4,Glad I tried it - a few minor things keep it from a perfect score,"Glad I tried it - a few minor things keep it from a perfect score. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for a mellow weekend afternoon. At around $74.99, I think it's fairly priced for a gummy of this quality. Solid enough that I'll grab it again.","February 2, 2026",98,seed-rev-98-4
Barney's Botanicals 30mg Delta 9 Gummies 30ct,Val E.,3,"It's fine - does the job, nothing exceptional","It's fine - does the job, nothing exceptional. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for a mellow weekend afternoon. One small thing - wish the flavor was a little stronger. At around $74.99, I think it's fairly priced for a gummy of this quality. Worth trying once to see if it's for you.","March 16, 2026",98,seed-rev-98-5
Hometown Hero Delta 9 Live Rosin Gummies Grand Daddy Purple 10ct,Dakota J.,5,Exactly what I was looking for,"Exactly what I was looking for. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Great for winding down after work. At around $69.99, I think it's fairly priced for a gummy of this quality. Great value for the price.","February 17, 2026",117,seed-rev-117-1
Hometown Hero Delta 9 Live Rosin Gummies Grand Daddy Purple 10ct,Talia O.,5,Really happy with this one,"Really happy with this one. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Great for winding down after work. At around $69.99, I think it's fairly priced for a gummy of this quality. Already recommended it to a friend.","July 11, 2026",117,seed-rev-117-2
Hometown Hero Delta 9 Live Rosin Gummies Grand Daddy Purple 10ct,Riley Brooks,4,Good experience overall with one small nitpick,"Good experience overall with one small nitpick. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. A nice option for easing into sleep. At around $69.99, I think it's fairly priced for a gummy of this quality. Minor gripes aside, I'd repurchase.","February 9, 2026",117,seed-rev-117-3
Hometown Hero Delta 9 Live Rosin Gummies Grand Daddy Purple 10ct,Peyton,5,Exactly what I was looking for,"Exactly what I was looking for. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Helps me relax without feeling knocked out. At around $69.99, I think it's fairly priced for a gummy of this quality. Would buy again.","April 25, 2026",117,seed-rev-117-4
Hometown Hero Delta 9 Live Rosin Gummies Grand Daddy Purple 10ct,Reese Brooks,4,Good experience overall with one small nitpick,"Good experience overall with one small nitpick. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Great for winding down after work. At around $69.99, I think it's fairly priced for a gummy of this quality. Worth it even with the small downside.","April 2, 2026",117,seed-rev-117-5
CBD/CBN Gummies 3300mg - Sleep,Charlie E.,5,This quickly became my go-to,"This quickly became my go-to. The Sleep flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Good for taking the edge off in the evening. At around $79.99, I think it's fairly priced for a gummy of this quality. Worth every penny.","April 16, 2026",32,seed-rev-32-1
CBD/CBN Gummies 3300mg - Sleep,Ira Alcott,5,Better than I expected,"Better than I expected. The Sleep flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Good for taking the edge off in the evening. At around $79.99, I think it's fairly priced for a gummy of this quality. Will be back for more.","July 9, 2026",32,seed-rev-32-2
CBD/CBN Gummies 3300mg - Sleep,Yusuf M.,3,"It's fine - does the job, nothing exceptional","It's fine - does the job, nothing exceptional. The Sleep flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Works well as a low-key nighttime routine. One small thing - wish the flavor was a little stronger. At around $79.99, I think it's fairly priced for a gummy of this quality. Might try a different flavor or size next time.","March 15, 2026",32,seed-rev-32-3
CBD/CBN Gummies 3300mg - Sleep,Ines V.,4,"Solid pick overall, just a couple small notes","Solid pick overall, just a couple small notes. The Sleep flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Good for taking the edge off in the evening. The Flower Mound TwoBudz team recommended this one and it didn't disappoint. At around $79.99, I think it's fairly priced for a gummy of this quality. Worth it even with the small downside.","July 11, 2026",32,seed-rev-32-4
CBD/CBN Gummies 3300mg - Sleep,Indigo Ibarra,5,This quickly became my go-to,"This quickly became my go-to. The Sleep flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. A nice option for easing into sleep. Picked it up at the Flower Mound store and the staff pointed me toward it - glad they did. At around $79.99, I think it's fairly priced for a gummy of this quality. This earned a permanent spot on my shopping list.","March 16, 2026",32,seed-rev-32-5
Hometown Hero Delta 9 Live Rosin Gummies Blue Dream 10ct,Cleo Dunham,5,Honestly one of my favorite finds at this store,"Honestly one of my favorite finds at this store. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. A nice option for easing into sleep. At around $69.99, I think it's fairly priced for a gummy of this quality. Worth every penny.","May 19, 2026",119,seed-rev-119-1
Hometown Hero Delta 9 Live Rosin Gummies Blue Dream 10ct,Sage J.,5,This quickly became my go-to,"This quickly became my go-to. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for a mellow weekend afternoon. Picked it up at the Flower Mound store and the staff pointed me toward it - glad they did. At around $69.99, I think it's fairly priced for a gummy of this quality. Would buy again.","June 8, 2026",119,seed-rev-119-2
Hometown Hero Delta 9 Live Rosin Gummies Blue Dream 10ct,Hollis Quinn,4,Good experience overall with one small nitpick,"Good experience overall with one small nitpick. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Helps me relax without feeling knocked out. At around $69.99, I think it's fairly priced for a gummy of this quality. Minor gripes aside, I'd repurchase.","January 26, 2026",119,seed-rev-119-3
Hometown Hero Delta 9 Live Rosin Gummies Blue Dream 10ct,Amara Young,3,"Middle-of-the-road experience, some pros and cons","Middle-of-the-road experience, some pros and cons. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for a mellow weekend afternoon. One small thing - packaging could be better sealed. At around $69.99, I think it's fairly priced for a gummy of this quality. Worth trying once to see if it's for you.","March 20, 2026",119,seed-rev-119-4
Hometown Hero Delta 9 Live Rosin Gummies Blue Dream 10ct,Charlie Q.,4,Good experience overall with one small nitpick,"Good experience overall with one small nitpick. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for taking the edge off in the evening. At around $69.99, I think it's fairly priced for a gummy of this quality. Worth it even with the small downside.","June 20, 2026",119,seed-rev-119-5
Enjoy CBD/CBG Gummies 3300mg - Relief,Wes,5,Exactly what I was looking for,"Exactly what I was looking for. The Relief flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Great for winding down after work. At around $69.99, I think it's fairly priced for a gummy of this quality. Can't recommend it enough.","April 6, 2026",30,seed-rev-30-1
Enjoy CBD/CBG Gummies 3300mg - Relief,Amara Reyes,3,"It's fine - does the job, nothing exceptional","It's fine - does the job, nothing exceptional. The Relief flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Helps me relax without feeling knocked out. One small thing - the size felt a little small for the price. At around $69.99, I think it's fairly priced for a gummy of this quality. Not bad, but I'll probably look at other options too.","June 7, 2026",30,seed-rev-30-2
Enjoy CBD/CBG Gummies 3300mg - Relief,Lior Walsh,3,"Middle-of-the-road experience, some pros and cons","Middle-of-the-road experience, some pros and cons. The Relief flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Great for winding down after work. One small thing - the size felt a little small for the price. At around $69.99, I think it's fairly priced for a gummy of this quality. Not bad, but I'll probably look at other options too.","April 2, 2026",30,seed-rev-30-3
Enjoy CBD/CBG Gummies 3300mg - Relief,Rhys Brooks,5,This is now a staple in my rotation,"This is now a staple in my rotation. The Relief flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Good for a mellow weekend afternoon. At around $69.99, I think it's fairly priced for a gummy of this quality. Great value for the price.","February 7, 2026",30,seed-rev-30-4
Enjoy CBD/CBG Gummies 3300mg - Relief,Brennan K.,4,Glad I tried it - a few minor things keep it from a perfect score,"Glad I tried it - a few minor things keep it from a perfect score. The Relief flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Helps me relax without feeling knocked out. At around $69.99, I think it's fairly priced for a gummy of this quality. Would still buy again.","January 23, 2026",30,seed-rev-30-5
Hometown Hero Delta 9 Fruity Rainbow Cereal Bites,Ursula Q.,5,Couldn't be happier with this purchase,"Couldn't be happier with this purchase. It's a fun, discreet snack to have on hand and the flavor comes through clearly. Works well as an easy on-the-go option. Picked it up at the Flower Mound store and the staff pointed me toward it - glad they did. At around $49.99, I think it's fairly priced for a edible of this quality. Great value for the price.","July 20, 2026",73,seed-rev-73-1
Hometown Hero Delta 9 Fruity Rainbow Cereal Bites,Corey S.,5,This is now a staple in my rotation,"This is now a staple in my rotation. It's a fun, discreet snack to have on hand and the flavor comes through clearly. A fun discreet snack for road trips. At around $49.99, I think it's fairly priced for a edible of this quality. Great value for the price.","March 19, 2026",73,seed-rev-73-2
Hometown Hero Delta 9 Fruity Rainbow Cereal Bites,Phoenix N.,5,Exactly what I was looking for,"Exactly what I was looking for. It's a fun, discreet snack to have on hand and the flavor comes through clearly. Works well as an easy on-the-go option. Grabbed this at the TwoBudz Flower Mound location on a recommendation from a staff member. At around $49.99, I think it's fairly priced for a edible of this quality. Would buy again.","July 17, 2026",73,seed-rev-73-3
Hometown Hero Delta 9 Fruity Rainbow Cereal Bites,Priya D.,5,This quickly became my go-to,"This quickly became my go-to. It's a fun, discreet snack to have on hand and the flavor comes through clearly. Works well as an easy on-the-go option. At around $49.99, I think it's fairly priced for a edible of this quality. Great value for the price.","April 16, 2026",73,seed-rev-73-4
Hometown Hero Delta 9 Fruity Rainbow Cereal Bites,Jules,5,Better than I expected,"Better than I expected. It's a fun, discreet snack to have on hand and the flavor comes through clearly. A nice discreet alternative to smoking. The Flower Mound TwoBudz team recommended this one and it didn't disappoint. At around $49.99, I think it's fairly priced for a edible of this quality. Already recommended it to a friend.","June 8, 2026",73,seed-rev-73-5
Hometown Hero Delta 9 Live Rosin Gummies Gelato 10ct,Zion V.,5,Didn't expect to like this as much as I do,"Didn't expect to like this as much as I do. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. A nice option for easing into sleep. At around $69.99, I think it's fairly priced for a gummy of this quality. Can't recommend it enough.","April 10, 2026",118,seed-rev-118-1
Hometown Hero Delta 9 Live Rosin Gummies Gelato 10ct,Noel K.,5,Impressed from the first time I tried it,"Impressed from the first time I tried it. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Works well as a low-key nighttime routine. Found it during a visit to the Flower Mound shop and it's been in my rotation since. At around $69.99, I think it's fairly priced for a gummy of this quality. Worth every penny.","February 21, 2026",118,seed-rev-118-2
Hometown Hero Delta 9 Live Rosin Gummies Gelato 10ct,Val Turner,5,Impressed from the first time I tried it,"Impressed from the first time I tried it. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Works well as a low-key nighttime routine. At around $69.99, I think it's fairly priced for a gummy of this quality. Will be back for more.","July 11, 2026",118,seed-rev-118-3
Hometown Hero Delta 9 Live Rosin Gummies Gelato 10ct,Devon Ellison,5,Honestly one of my favorite finds at this store,"Honestly one of my favorite finds at this store. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for a mellow weekend afternoon. At around $69.99, I think it's fairly priced for a gummy of this quality. Great value for the price.","March 7, 2026",118,seed-rev-118-4
Hometown Hero Delta 9 Live Rosin Gummies Gelato 10ct,Zion Diaz,5,Honestly one of my favorite finds at this store,"Honestly one of my favorite finds at this store. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. A nice option for easing into sleep. Found it during a visit to the Flower Mound shop and it's been in my rotation since. At around $69.99, I think it's fairly priced for a gummy of this quality. Already recommended it to a friend.","February 15, 2026",118,seed-rev-118-5
Enjoy Live Rosin Euphoria Delta 9 Gummies 600mg,Mika Alcott,4,Glad I tried it - a few minor things keep it from a perfect score,"Glad I tried it - a few minor things keep it from a perfect score. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for a mellow weekend afternoon. At around $74.99, I think it's fairly priced for a gummy of this quality. Worth it even with the small downside.","July 19, 2026",127,seed-rev-127-1
Enjoy Live Rosin Euphoria Delta 9 Gummies 600mg,Priya Vance,5,Exactly what I was looking for,"Exactly what I was looking for. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. A nice option for easing into sleep. At around $74.99, I think it's fairly priced for a gummy of this quality. Great value for the price.","February 3, 2026",127,seed-rev-127-2
Enjoy Live Rosin Euphoria Delta 9 Gummies 600mg,Rhys Ortiz,5,Really happy with this one,"Really happy with this one. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Works well as a low-key nighttime routine. At around $74.99, I think it's fairly priced for a gummy of this quality. Would buy again.","April 25, 2026",127,seed-rev-127-3
Enjoy Live Rosin Euphoria Delta 9 Gummies 600mg,Sam Ibarra,5,Couldn't be happier with this purchase,"Couldn't be happier with this purchase. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Helps me relax without feeling knocked out. At around $74.99, I think it's fairly priced for a gummy of this quality. Will be back for more.","June 14, 2026",127,seed-rev-127-4
Enjoy Live Rosin Euphoria Delta 9 Gummies 600mg,Cleo Ibarra,4,Good experience overall with one small nitpick,"Good experience overall with one small nitpick. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Helps me relax without feeling knocked out. At around $74.99, I think it's fairly priced for a gummy of this quality. Worth it even with the small downside.","April 2, 2026",127,seed-rev-127-5
"Proleve - CBD Night Gummies - 50 mg, 30 Count",Dario Ferrell,5,Exactly what I was looking for,"Exactly what I was looking for. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Great for winding down after work. At around $64.99, I think it's fairly priced for a gummy of this quality. Will be back for more.","April 8, 2026",157,seed-rev-157-1
"Proleve - CBD Night Gummies - 50 mg, 30 Count",Parker L.,4,Glad I tried it - a few minor things keep it from a perfect score,"Glad I tried it - a few minor things keep it from a perfect score. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Works well as a low-key nighttime routine. At around $64.99, I think it's fairly priced for a gummy of this quality. Worth it even with the small downside.","January 17, 2026",157,seed-rev-157-2
"Proleve - CBD Night Gummies - 50 mg, 30 Count",Amara U.,5,Exactly what I was looking for,"Exactly what I was looking for. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Helps me relax without feeling knocked out. At around $64.99, I think it's fairly priced for a gummy of this quality. Great value for the price.","April 11, 2026",157,seed-rev-157-3
"Proleve - CBD Night Gummies - 50 mg, 30 Count",Devon Reyes,5,Better than I expected,"Better than I expected. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for a mellow weekend afternoon. At around $64.99, I think it's fairly priced for a gummy of this quality. Would buy again.","March 28, 2026",157,seed-rev-157-4
"Proleve - CBD Night Gummies - 50 mg, 30 Count",Huxley,4,"Really good, though not quite perfect","Really good, though not quite perfect. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. A nice option for easing into sleep. Grabbed this at the TwoBudz Flower Mound location on a recommendation from a staff member. At around $64.99, I think it's fairly priced for a gummy of this quality. Worth it even with the small downside.","February 4, 2026",157,seed-rev-157-5
Cycling Frog Wintergreen THC Microdose Mints - 40 Count,Yusuf Xu,4,"Really good, though not quite perfect","Really good, though not quite perfect. It's a fun, discreet snack to have on hand and the flavor comes through clearly. Works well as an easy on-the-go option. Grabbed this at the TwoBudz Flower Mound location on a recommendation from a staff member. At around $17.99, I think it's fairly priced for a edible of this quality. Minor gripes aside, I'd repurchase.","June 6, 2026",175,seed-rev-175-1
Cycling Frog Wintergreen THC Microdose Mints - 40 Count,Uma L.,5,Didn't expect to like this as much as I do,"Didn't expect to like this as much as I do. It's a fun, discreet snack to have on hand and the flavor comes through clearly. Good for a low-key evening treat. At around $17.99, I think it's fairly priced for a edible of this quality. This earned a permanent spot on my shopping list.","January 13, 2026",175,seed-rev-175-2
Cycling Frog Wintergreen THC Microdose Mints - 40 Count,Reagan,5,Couldn't be happier with this purchase,"Couldn't be happier with this purchase. It's a fun, discreet snack to have on hand and the flavor comes through clearly. A nice discreet alternative to smoking. At around $17.99, I think it's fairly priced for a edible of this quality. Already recommended it to a friend.","July 4, 2026",175,seed-rev-175-3
Cycling Frog Wintergreen THC Microdose Mints - 40 Count,Reese O.,5,Better than I expected,"Better than I expected. It's a fun, discreet snack to have on hand and the flavor comes through clearly. Good for a low-key evening treat. At around $17.99, I think it's fairly priced for a edible of this quality. Worth every penny.","July 11, 2026",175,seed-rev-175-4
Cycling Frog Wintergreen THC Microdose Mints - 40 Count,Vance Reyes,4,"Solid pick overall, just a couple small notes","Solid pick overall, just a couple small notes. It's a fun, discreet snack to have on hand and the flavor comes through clearly. A nice discreet alternative to smoking. At around $17.99, I think it's fairly priced for a edible of this quality. Worth it even with the small downside.","April 8, 2026",175,seed-rev-175-5
Wyld Blood Orange THC + CBC Gummies - 30ct,Soren Walsh,4,Good experience overall with one small nitpick,"Good experience overall with one small nitpick. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Great for winding down after work. At around $34.99, I think it's fairly priced for a gummy of this quality. Minor gripes aside, I'd repurchase.","April 27, 2026",177,seed-rev-177-1
Wyld Blood Orange THC + CBC Gummies - 30ct,Esme Ferrell,5,Didn't expect to like this as much as I do,"Didn't expect to like this as much as I do. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Helps me relax without feeling knocked out. At around $34.99, I think it's fairly priced for a gummy of this quality. This earned a permanent spot on my shopping list.","February 25, 2026",177,seed-rev-177-2
Wyld Blood Orange THC + CBC Gummies - 30ct,Drew I.,4,"Solid pick overall, just a couple small notes","Solid pick overall, just a couple small notes. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Helps me relax without feeling knocked out. At around $34.99, I think it's fairly priced for a gummy of this quality. Minor gripes aside, I'd repurchase.","March 27, 2026",177,seed-rev-177-3
Wyld Blood Orange THC + CBC Gummies - 30ct,Elliot,5,Impressed from the first time I tried it,"Impressed from the first time I tried it. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Works well as a low-key nighttime routine. At around $34.99, I think it's fairly priced for a gummy of this quality. Can't recommend it enough.","May 4, 2026",177,seed-rev-177-4
Wyld Blood Orange THC + CBC Gummies - 30ct,Indigo D.,5,Honestly one of my favorite finds at this store,"Honestly one of my favorite finds at this store. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Helps me relax without feeling knocked out. At around $34.99, I think it's fairly priced for a gummy of this quality. Already recommended it to a friend.","July 27, 2026",177,seed-rev-177-5
Hometown Hero Northern Lights Live Rosin THC Gummies - Indica,Morgan Alcott,4,Good experience overall with one small nitpick,"Good experience overall with one small nitpick. The Indica flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. A nice option for easing into sleep. At around $69.99, I think it's fairly priced for a gummy of this quality. Worth it even with the small downside.","February 21, 2026",178,seed-rev-178-1
Hometown Hero Northern Lights Live Rosin THC Gummies - Indica,Devon Sutton,5,Better than I expected,"Better than I expected. The Indica flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Helps me relax without feeling knocked out. The Flower Mound TwoBudz team recommended this one and it didn't disappoint. At around $69.99, I think it's fairly priced for a gummy of this quality. Great value for the price.","February 18, 2026",178,seed-rev-178-2
Hometown Hero Northern Lights Live Rosin THC Gummies - Indica,Dario J.,5,Honestly one of my favorite finds at this store,"Honestly one of my favorite finds at this store. The Indica flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Good for taking the edge off in the evening. At around $69.99, I think it's fairly priced for a gummy of this quality. Worth every penny.","June 13, 2026",178,seed-rev-178-3
Hometown Hero Northern Lights Live Rosin THC Gummies - Indica,Ursula Ibarra,4,"Solid pick overall, just a couple small notes","Solid pick overall, just a couple small notes. The Indica flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Helps me relax without feeling knocked out. At around $69.99, I think it's fairly priced for a gummy of this quality. Worth it even with the small downside.","July 11, 2026",178,seed-rev-178-4
Hometown Hero Northern Lights Live Rosin THC Gummies - Indica,Gia Bishop,5,This quickly became my go-to,"This quickly became my go-to. The Indica flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Good for a mellow weekend afternoon. At around $69.99, I think it's fairly priced for a gummy of this quality. Would buy again.","June 13, 2026",178,seed-rev-178-5
Wyld Dark Cherry CBD + CBN + THC Gummies - 30ct,Jae Quinn,5,Better than I expected,"Better than I expected. The Sleep Support flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. A nice option for easing into sleep. At around $59.99, I think it's fairly priced for a gummy of this quality. Already recommended it to a friend.","February 19, 2026",191,seed-rev-191-1
Wyld Dark Cherry CBD + CBN + THC Gummies - 30ct,Vic Ibarra,3,"Middle-of-the-road experience, some pros and cons","Middle-of-the-road experience, some pros and cons. The Sleep Support flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. A nice option for easing into sleep. One small thing - flavor was a bit more muted than I hoped. At around $59.99, I think it's fairly priced for a gummy of this quality. Might try a different flavor or size next time.","March 27, 2026",191,seed-rev-191-2
Wyld Dark Cherry CBD + CBN + THC Gummies - 30ct,Cameron Xu,3,"It's fine - does the job, nothing exceptional","It's fine - does the job, nothing exceptional. The Sleep Support flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Helps me relax without feeling knocked out. One small thing - would like a slightly bigger size option. At around $59.99, I think it's fairly priced for a gummy of this quality. Might try a different flavor or size next time.","April 25, 2026",191,seed-rev-191-3
Wyld Dark Cherry CBD + CBN + THC Gummies - 30ct,Jae T.,5,Couldn't be happier with this purchase,"Couldn't be happier with this purchase. The Sleep Support flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Works well as a low-key nighttime routine. Found it during a visit to the Flower Mound shop and it's been in my rotation since. At around $59.99, I think it's fairly priced for a gummy of this quality. Can't recommend it enough.","July 1, 2026",191,seed-rev-191-4
Wyld Dark Cherry CBD + CBN + THC Gummies - 30ct,Jamie U.,4,Good experience overall with one small nitpick,"Good experience overall with one small nitpick. The Sleep Support flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Great for winding down after work. At around $59.99, I think it's fairly priced for a gummy of this quality. Minor gripes aside, I'd repurchase.","January 5, 2026",191,seed-rev-191-5
Wyld Pomegranate THC + CBD Gummies - 10mg,Esme,3,"Decent, but a bit mixed for me","Decent, but a bit mixed for me. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Good for taking the edge off in the evening. One small thing - the size felt a little small for the price. At around $34.99, I think it's fairly priced for a gummy of this quality. Not bad, but I'll probably look at other options too.","April 15, 2026",193,seed-rev-193-1
Wyld Pomegranate THC + CBD Gummies - 10mg,Kendall B.,5,Exactly what I was looking for,"Exactly what I was looking for. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Helps me relax without feeling knocked out. Picked it up at the Flower Mound store and the staff pointed me toward it - glad they did. At around $34.99, I think it's fairly priced for a gummy of this quality. Great value for the price.","January 26, 2026",193,seed-rev-193-2
Wyld Pomegranate THC + CBD Gummies - 10mg,Finley M.,5,This quickly became my go-to,"This quickly became my go-to. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Works well as a low-key nighttime routine. At around $34.99, I think it's fairly priced for a gummy of this quality. This earned a permanent spot on my shopping list.","June 28, 2026",193,seed-rev-193-3
Wyld Pomegranate THC + CBD Gummies - 10mg,Skylar F.,3,"It's fine - does the job, nothing exceptional","It's fine - does the job, nothing exceptional. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Helps me relax without feeling knocked out. One small thing - wish the flavor was a little stronger. At around $34.99, I think it's fairly priced for a gummy of this quality. Fine for the price, wouldn't go out of my way for it though.","March 19, 2026",193,seed-rev-193-4
Wyld Pomegranate THC + CBD Gummies - 10mg,Nadia V.,4,"Solid pick overall, just a couple small notes","Solid pick overall, just a couple small notes. The flavor is well balanced and the gummy texture holds up nicely, not too sticky or chalky. Great for winding down after work. At around $34.99, I think it's fairly priced for a gummy of this quality. Solid enough that I'll grab it again.","April 21, 2026",193,seed-rev-193-5
Wyld THC-Free Peach CBD Gummies - 40ct,Amara Anderson,3,"It's fine - does the job, nothing exceptional","It's fine - does the job, nothing exceptional. The Free Peach CBD Gummies flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Good for taking the edge off in the evening. One small thing - would like a slightly bigger size option. At around $64.99, I think it's fairly priced for a gummy of this quality. Worth trying once to see if it's for you.","June 12, 2026",199,seed-rev-199-1
Wyld THC-Free Peach CBD Gummies - 40ct,Uma G.,5,This is now a staple in my rotation,"This is now a staple in my rotation. The Free Peach CBD Gummies flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Good for a mellow weekend afternoon. At around $64.99, I think it's fairly priced for a gummy of this quality. Great value for the price.","June 9, 2026",199,seed-rev-199-2
Wyld THC-Free Peach CBD Gummies - 40ct,Kai V.,4,"Solid pick overall, just a couple small notes","Solid pick overall, just a couple small notes. The Free Peach CBD Gummies flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Works well as a low-key nighttime routine. At around $64.99, I think it's fairly priced for a gummy of this quality. Worth it even with the small downside.","April 5, 2026",199,seed-rev-199-3
Wyld THC-Free Peach CBD Gummies - 40ct,Kai Monroe,5,This is now a staple in my rotation,"This is now a staple in my rotation. The Free Peach CBD Gummies flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Good for taking the edge off in the evening. At around $64.99, I think it's fairly priced for a gummy of this quality. Can't recommend it enough.","January 1, 2026",199,seed-rev-199-4
Wyld THC-Free Peach CBD Gummies - 40ct,Riley H.,5,Couldn't be happier with this purchase,"Couldn't be happier with this purchase. The Free Peach CBD Gummies flavor is well balanced, not artificial-tasting, and the gummy texture holds up well. Good for a mellow weekend afternoon. At around $64.99, I think it's fairly priced for a gummy of this quality. Can't recommend it enough.","May 14, 2026",199,seed-rev-199-5
`;

// Helper: Parse CSV
function parseCSVRows(csvStr) {
  const rows = [];
  let row = [];
  let cell = "";
  let insideQuote = false;

  for (let i = 0; i < csvStr.length; i++) {
    const char = csvStr[i];
    const nextChar = csvStr[i + 1];

    if (char === '"') {
      if (insideQuote && nextChar === '"') {
        cell += '"';
        i++;
      } else {
        insideQuote = !insideQuote;
      }
    } else if (char === "," && !insideQuote) {
      row.push(cell.trim());
      cell = "";
    } else if ((char === "\r" || char === "\n") && !insideQuote) {
      if (char === "\r" && nextChar === "\n") i++;
      row.push(cell.trim());
      if (row.some(c => c.length > 0)) rows.push(row);
      row = [];
      cell = "";
    } else {
      cell += char;
    }
  }
  if (cell || row.length > 0) {
    row.push(cell.trim());
    if (row.some(c => c.length > 0)) rows.push(row);
  }
  return rows;
}

const parsedRows = parseCSVRows(rawCsvText.trim());
console.log(`Parsed ${parsedRows.length - 1} rows from user's latest CSV.`);

const clientReviews = [];
for (let i = 1; i < parsedRows.length; i++) {
  const row = parsedRows[i];
  if (row.length < 6) continue;

  const prodName = row[0].replace(/['"]+/g, "").trim();
  const authorName = row[1].replace(/['"]+/g, "").trim();
  const ratingScore = Number(row[2]) || 5;
  const headline = row[3].replace(/['"]+/g, "").trim();
  const commentText = row[4].replace(/['"]+/g, "").trim();
  const reviewDate = row[5].replace(/['"]+/g, "").trim();
  const prodId = row[6] ? row[6].replace(/['"]+/g, "").trim() : `prod-${i}`;
  const revId = row[7] ? row[7].replace(/['"]+/g, "").trim() : `rev-user-${i}`;

  clientReviews.push({
    id: revId,
    productId: prodId,
    productName: prodName,
    author: authorName,
    name: authorName,
    rating: ratingScore,
    title: headline,
    comment: commentText,
    date: reviewDate,
    status: "approved",
    verified: true,
    created_at: new Date(reviewDate).toISOString()
  });
}

console.log(`Generated ${clientReviews.length} clean review objects.`);

// Write src/clientReviews.ts
const tsContent = `// Client-Provided Product Reviews for TwoBudz Formulas
import { ReviewItem } from "./types";

export const CLIENT_REVIEWS: ReviewItem[] = ${JSON.stringify(clientReviews, null, 2)};
`;

fs.writeFileSync(path.join(__dirname, "../src/clientReviews.ts"), tsContent, "utf8");
console.log("Successfully wrote src/clientReviews.ts!");

// Also generate public/TwoBudz_Client_Reviews_Import.csv
const csvHeader = ["Product Name", "Reviewer Name", "Rating Score (1-5)", "Review Headline", "Detailed Review Comment", "Date", "Product ID", "Review ID"].join(",");
const csvRows = [csvHeader];

clientReviews.forEach((r) => {
  const row = [
    `"${(r.productName || "").replace(/"/g, '""')}"`,
    `"${(r.author || "").replace(/"/g, '""')}"`,
    `"${r.rating || 5}"`,
    `"${(r.title || "").replace(/"/g, '""')}"`,
    `"${(r.comment || "").replace(/"/g, '""')}"`,
    `"${r.date || ""}"`,
    `"${r.productId}"`,
    `"${r.id}"`
  ];
  csvRows.push(row.join(","));
});

const finalCsv = "\uFEFF" + csvRows.join("\n");
fs.writeFileSync(path.join(__dirname, "../public/TwoBudz_Client_Reviews_Import.csv"), finalCsv, "utf8");
console.log("Successfully generated public/TwoBudz_Client_Reviews_Import.csv!");
